/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author DELL
 */
public class Form_Home extends javax.swing.JFrame {
// Variables declaration - do not modify
// End of variables declaration
    /**
     * Creates new form form_design_system
     */
    public Form_Home() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
        applyRole();
        if(pnl_DangNhap.maVT != null && pnl_DangNhap.maVT.equalsIgnoreCase("ADMIN")){
            Pnl_2_ThongKeSanPham panel= new Pnl_2_ThongKeSanPham();
            showPanel(panel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGrp_1 = new javax.swing.ButtonGroup();
        pnl_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_sidebar = new javax.swing.JPanel();
        btn_formDoanhThu = new javax.swing.JButton();
        btn_formSanPham = new javax.swing.JButton();
        btn_formHoaDon = new javax.swing.JButton();
        btn_formHeThong = new javax.swing.JButton();
        btn_formNhanVien = new javax.swing.JButton();
        btn_formKhachHang = new javax.swing.JButton();
        btn_formLichSu = new javax.swing.JButton();
        btn_formKhuyenMai = new javax.swing.JButton();
        btn_formDangNhap = new javax.swing.JButton();
        pnl_body = new javax.swing.JPanel();
        section_1 = new javax.swing.JTabbedPane();
        section_1_tab_1 = new javax.swing.JPanel();
        bar_search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_obj = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        section_2 = new javax.swing.JTabbedPane();
        section_2_tab_1 = new javax.swing.JPanel();
        section_2_tab_2 = new javax.swing.JPanel();
        field_1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        field_2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        field_3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        field_4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        field_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        section_2_tab_3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_header.setBackground(new java.awt.Color(11, 137, 90));
        pnl_header.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("App Logo");
        pnl_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 0, -1, -1));

        getContentPane().add(pnl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        pnl_sidebar.setBackground(new java.awt.Color(11, 137, 90));
        pnl_sidebar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_formDoanhThu.setBackground(new java.awt.Color(14, 159, 103));
        btn_formDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        btn_formDoanhThu.setText("Doanh Thu");
        btn_formDoanhThu.setBorder(null);
        btn_formDoanhThu.setBorderPainted(false);
        btn_formDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formDoanhThuActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 32));

        btn_formSanPham.setBackground(new java.awt.Color(14, 159, 103));
        btn_formSanPham.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btn_formSanPham.setText("Sản Phẩm");
        btn_formSanPham.setBorder(null);
        btn_formSanPham.setBorderPainted(false);
        btn_formSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formSanPhamActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 200, 32));

        btn_formHoaDon.setBackground(new java.awt.Color(14, 159, 103));
        btn_formHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_formHoaDon.setText("Quản lý bán hàng ");
        btn_formHoaDon.setBorder(null);
        btn_formHoaDon.setBorderPainted(false);
        btn_formHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formHoaDonActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 200, 32));

        btn_formHeThong.setBackground(new java.awt.Color(14, 159, 103));
        btn_formHeThong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formHeThong.setForeground(new java.awt.Color(255, 255, 255));
        btn_formHeThong.setText("Hệ Thống");
        btn_formHeThong.setBorder(null);
        btn_formHeThong.setBorderPainted(false);
        btn_formHeThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formHeThongActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formHeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 200, 32));

        btn_formNhanVien.setBackground(new java.awt.Color(14, 159, 103));
        btn_formNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btn_formNhanVien.setText("Nhân Viên");
        btn_formNhanVien.setBorder(null);
        btn_formNhanVien.setBorderPainted(false);
        btn_formNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formNhanVienActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 200, 32));

        btn_formKhachHang.setBackground(new java.awt.Color(14, 159, 103));
        btn_formKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_formKhachHang.setText("Khách Hàng");
        btn_formKhachHang.setBorder(null);
        btn_formKhachHang.setBorderPainted(false);
        btn_formKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formKhachHangActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 200, 32));

        btn_formLichSu.setBackground(new java.awt.Color(14, 159, 103));
        btn_formLichSu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formLichSu.setForeground(new java.awt.Color(255, 255, 255));
        btn_formLichSu.setText("Lịch Sử");
        btn_formLichSu.setBorder(null);
        btn_formLichSu.setBorderPainted(false);
        btn_formLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formLichSuActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formLichSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 32));

        btn_formKhuyenMai.setBackground(new java.awt.Color(14, 159, 103));
        btn_formKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        btn_formKhuyenMai.setText("Khuyến Mãi");
        btn_formKhuyenMai.setBorder(null);
        btn_formKhuyenMai.setBorderPainted(false);
        btn_formKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formKhuyenMaiActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_formKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 200, 32));

        btn_formDangNhap.setBackground(new java.awt.Color(14, 159, 103));
        btn_formDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_formDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_formDangNhap.setText("Đăng Nhập");
        btn_formDangNhap.setBorder(null);
        btn_formDangNhap.setBorderPainted(false);
        pnl_sidebar.add(btn_formDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 200, 32));

        getContentPane().add(pnl_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 680));

        pnl_body.setBackground(new java.awt.Color(235, 249, 245));
        pnl_body.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        section_1.setToolTipText("tab");

        section_1_tab_1.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_1.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar_search.setBackground(new java.awt.Color(38, 159, 114));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tìm kiếm sản phẩm");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout bar_searchLayout = new javax.swing.GroupLayout(bar_search);
        bar_search.setLayout(bar_searchLayout);
        bar_searchLayout.setHorizontalGroup(
            bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bar_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bar_searchLayout.setVerticalGroup(
            bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bar_searchLayout.createSequentialGroup()
                .addGroup(bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        section_1_tab_1.add(bar_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, 290, 20));

        tbl_obj.setForeground(new java.awt.Color(239, 244, 242));
        tbl_obj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_obj);

        section_1_tab_1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 587, 560));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("DANH SÁCH SẢN PHẨM");
        section_1_tab_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        section_1.addTab("Thông tin chi tiết", section_1_tab_1);

        pnl_body.add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, -5, 613, 672));

        section_2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_2.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_2.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_1.setBackground(new java.awt.Color(250, 250, 250));
        field_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_1.setForeground(new java.awt.Color(250, 250, 250));
        field_1.setPreferredSize(new java.awt.Dimension(386, 637));
        field_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 159, 103));
        jLabel6.setText("Mã sản phẩm:");
        field_1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jTextField2.setText("jTextField2");
        field_1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 20));

        field_2.setBackground(new java.awt.Color(255, 255, 255));
        field_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_2.setForeground(new java.awt.Color(250, 250, 250));
        field_2.setPreferredSize(new java.awt.Dimension(386, 637));
        field_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 159, 103));
        jLabel7.setText("Tên sản phẩm");
        field_2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jTextField3.setText("jTextField2");
        field_2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 20));

        field_3.setBackground(new java.awt.Color(250, 250, 250));
        field_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_3.setForeground(new java.awt.Color(250, 250, 250));
        field_3.setPreferredSize(new java.awt.Dimension(386, 637));
        field_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 159, 103));
        jLabel8.setText("Loại sản phẩm:");
        field_3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        field_3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 20));

        field_4.setBackground(new java.awt.Color(255, 255, 255));
        field_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_4.setForeground(new java.awt.Color(250, 250, 250));
        field_4.setPreferredSize(new java.awt.Dimension(386, 637));
        field_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(14, 159, 103));
        jLabel9.setText("Loại thuộc tính:");
        field_4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        rdoGrp_1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        field_4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        rdoGrp_1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jRadioButton2.setText("jRadioButton1");
        field_4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 19, 240, 17));

        rdoGrp_1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jRadioButton3.setText("jRadioButton1");
        field_4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 38, 240, 17));

        section_2_tab_2.add(field_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 60));

        field_5.setBackground(new java.awt.Color(250, 250, 250));
        field_5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_5.setForeground(new java.awt.Color(250, 250, 250));
        field_5.setPreferredSize(new java.awt.Dimension(386, 637));
        field_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 159, 103));
        jLabel10.setText("...");
        field_5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jTextField4.setText("jTextField2");
        field_5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 20));

        section_2_tab_1.add(section_2_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, 360, 394));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thông tin");
        section_2_tab_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, 15));

        section_2_tab_3.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(14, 159, 103));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        section_2_tab_3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, 333, 16));

        section_2_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 442, 360, 180));

        section_2.addTab("Chi tiết", section_2_tab_1);

        pnl_body.add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, -5, 386, 672));

        getContentPane().add(pnl_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 1080, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_formDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formDoanhThuActionPerformed
        // TODO add your handling code here:
//        pnl_body.removeAll();
//        Pnl_Template panel = new Pnl_Template(); //để view lên form thì phải khai báo pannel của mình ra
//        this.showPanel(panel);
        // TODO add your handling code here:
        pnl_body.removeAll();
        Pnl_2_ThongKeSanPham panel = new Pnl_2_ThongKeSanPham(); //để view lên form thì phải khai báo pannel của mình ra
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formDoanhThuActionPerformed

    private void btn_formHeThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formHeThongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_formHeThongActionPerformed

    private void btn_formKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formKhuyenMaiActionPerformed
        // TODO add your handling code here:
        pnl_body.removeAll();
        Pnl_8_PhieuGiamGia panel = new Pnl_8_PhieuGiamGia(); //để view lên form thì phải khai báo pannel của mình ra
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formKhuyenMaiActionPerformed

    private void btn_formHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formHoaDonActionPerformed
        // TODO add your handling code here:
        pnl_body.removeAll();
        Pnl_6_qlHoaDon panel = new Pnl_6_qlHoaDon(); //để view lên form thì phải khai báo pannel của mình ra
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formHoaDonActionPerformed

    private void btn_formKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formKhachHangActionPerformed
        // TODO add your handling code here:
        pnl_body.removeAll();
        Pnl_5_qlKhachHang panel = new Pnl_5_qlKhachHang();
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formKhachHangActionPerformed

    private void btn_formNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formNhanVienActionPerformed
        // TODO add your handling code here:
        pnl_body.removeAll();
        pnl_4_NhanVien panel = new pnl_4_NhanVien();
//        Pnl_4_qlNhanVien panel = new Pnl_4_qlNhanVien();
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formNhanVienActionPerformed

    private void btn_formLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formLichSuActionPerformed
        // TODO add your handling code here:
        pnl_body.removeAll();
        Pnl_7_LichSuHoaDon panel = new Pnl_7_LichSuHoaDon();
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formLichSuActionPerformed

    private void btn_formSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formSanPhamActionPerformed
        // TODO add your handling code here:
        pnl_body.removeAll();
        Pnl_3_qlSanPham panel = new Pnl_3_qlSanPham();
        this.showPanel(panel);
    }//GEN-LAST:event_btn_formSanPhamActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void initDefaultUI() {
        setVisible(true);
    }
 
    public void showPanel(javax.swing.JPanel panel) {
        pnl_body.removeAll();
        pnl_body.setLayout(new java.awt.BorderLayout());
        pnl_body.add(panel, java.awt.BorderLayout.CENTER);
        pnl_body.revalidate();
        pnl_body.repaint();
    }
    private void applyRole() {

    String role = pnl_DangNhap.maVT;

    if (role == null || role.isEmpty()) return;

    System.out.println("ROLE LOGIN = " + role);

    if (role.equalsIgnoreCase("ADMIN")) {
        return;
    }

    btn_formSanPham.setEnabled(false);
    btn_formNhanVien.setEnabled(false);
    btn_formDoanhThu.setEnabled(false);
    btn_formKhuyenMai.setEnabled(false);
    btn_formHeThong.setEnabled(false);
    btn_formLichSu.setEnabled(false);

}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar_search;
    private javax.swing.JButton btn_formDangNhap;
    private javax.swing.JButton btn_formDoanhThu;
    private javax.swing.JButton btn_formHeThong;
    private javax.swing.JButton btn_formHoaDon;
    private javax.swing.JButton btn_formKhachHang;
    private javax.swing.JButton btn_formKhuyenMai;
    private javax.swing.JButton btn_formLichSu;
    private javax.swing.JButton btn_formNhanVien;
    private javax.swing.JButton btn_formSanPham;
    private javax.swing.JPanel field_1;
    private javax.swing.JPanel field_2;
    private javax.swing.JPanel field_3;
    private javax.swing.JPanel field_4;
    private javax.swing.JPanel field_5;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel pnl_body;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.ButtonGroup rdoGrp_1;
    private javax.swing.JTabbedPane section_1;
    private javax.swing.JPanel section_1_tab_1;
    private javax.swing.JTabbedPane section_2;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_2;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JTable tbl_obj;
    // End of variables declaration//GEN-END:variables
}
