/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import com.formdev.flatlaf.FlatLightLaf;
import controller.Controller_NhanVien;
import daoipml.DaoImpl_NhanVien;
import entity.NhanVien;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class pnl_4_NhanVien extends javax.swing.JPanel implements Controller_NhanVien{

    /**
     * Creates new form panel_1_sanPhamA
     */
     private DefaultTableModel model = new DefaultTableModel();
    private DaoImpl_NhanVien repoNV = new DaoImpl_NhanVien();
    private int index = -1;
    public pnl_4_NhanVien() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        initComponents();
        txt_name_rieng.setVisible(false);
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdo_tk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        section_1 = new javax.swing.JTabbedPane();
        section_1_tab_1 = new javax.swing.JPanel();
        bar_search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_timkiemnv = new javax.swing.JButton();
        tbl_nv = new javax.swing.JScrollPane();
        tbl_nhanvien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_name_rieng = new javax.swing.JTextField();
        rdo_nam_rienh = new javax.swing.JRadioButton();
        rdo_nu_rieng = new javax.swing.JRadioButton();
        rdo_all_rieng = new javax.swing.JRadioButton();
        section_2 = new javax.swing.JTabbedPane();
        section_2_tab_1 = new javax.swing.JPanel();
        section_2_tab_2 = new javax.swing.JPanel();
        field_1 = new javax.swing.JPanel();
        txt_ma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        field_2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        field_3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        field_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        field_9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        field_14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        field_17 = new javax.swing.JPanel();
        txt_tk = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        field_10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_ngaySinh = new javax.swing.JTextField();
        field_21 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txt_mk = new javax.swing.JTextField();
        field_8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        section_2_tab_3 = new javax.swing.JPanel();
        btn_xoa = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 249, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_1.setToolTipText("tab");

        section_1_tab_1.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_1.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar_search.setBackground(new java.awt.Color(38, 159, 114));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tìm kiếm ");

        btn_timkiemnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemnvMouseClicked(evt);
            }
        });
        btn_timkiemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bar_searchLayout = new javax.swing.GroupLayout(bar_search);
        bar_search.setLayout(bar_searchLayout);
        bar_searchLayout.setHorizontalGroup(
            bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bar_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timkiemnv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        bar_searchLayout.setVerticalGroup(
            bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bar_searchLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_timkiemnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        section_1_tab_1.add(bar_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, 290, 20));

        tbl_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nvMouseClicked(evt);
            }
        });

        tbl_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NV", "Họ tên", "CCCD", "Email", "SDT", "Giới tính", "Địa chỉ", "Ngày sinh"
            }
        ));
        tbl_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanvienMouseClicked(evt);
            }
        });
        tbl_nv.setViewportView(tbl_nhanvien);
        if (tbl_nhanvien.getColumnModel().getColumnCount() > 0) {
            tbl_nhanvien.getColumnModel().getColumn(0).setResizable(false);
            tbl_nhanvien.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbl_nhanvien.getColumnModel().getColumn(2).setResizable(false);
            tbl_nhanvien.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        section_1_tab_1.add(tbl_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 590, 560));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 71, 46));
        jLabel3.setText("DANH SÁCH NHÂN VIÊN");
        section_1_tab_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        jLabel1.setText("Nhập tên");

        txt_name_rieng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name_riengActionPerformed(evt);
            }
        });

        rdo_tk.add(rdo_nam_rienh);
        rdo_nam_rienh.setText("nam");
        rdo_nam_rienh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nam_rienhActionPerformed(evt);
            }
        });

        rdo_tk.add(rdo_nu_rieng);
        rdo_nu_rieng.setText("nữ");
        rdo_nu_rieng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nu_riengActionPerformed(evt);
            }
        });

        rdo_tk.add(rdo_all_rieng);
        rdo_all_rieng.setSelected(true);
        rdo_all_rieng.setText("all");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_name_rieng, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdo_nam_rienh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_nu_rieng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_all_rieng)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_name_rieng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_nam_rienh)
                    .addComponent(rdo_nu_rieng)
                    .addComponent(rdo_all_rieng))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        section_1_tab_1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        section_1.addTab("Thông tin chi tiết", section_1_tab_1);

        jPanel1.add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, -5, 613, 672));

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_2.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_2.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_1.setBackground(new java.awt.Color(250, 250, 250));
        field_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_1.setForeground(new java.awt.Color(250, 250, 250));
        field_1.setPreferredSize(new java.awt.Dimension(386, 637));
        field_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_1.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(14, 159, 103));
        jLabel12.setText("Mã nhân viên");
        field_1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        section_2_tab_2.add(field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 20));

        field_2.setBackground(new java.awt.Color(255, 255, 255));
        field_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_2.setForeground(new java.awt.Color(250, 250, 250));
        field_2.setPreferredSize(new java.awt.Dimension(386, 637));
        field_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 159, 103));
        jLabel7.setText("Họ tên nhân viên");
        field_2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_2.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 20));

        field_3.setBackground(new java.awt.Color(250, 250, 250));
        field_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_3.setForeground(new java.awt.Color(250, 250, 250));
        field_3.setPreferredSize(new java.awt.Dimension(386, 637));
        field_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 159, 103));
        jLabel8.setText("CCCD");
        field_3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        txt_cccd.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_3.add(txt_cccd, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 20));

        field_5.setBackground(new java.awt.Color(250, 250, 250));
        field_5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_5.setForeground(new java.awt.Color(250, 250, 250));
        field_5.setPreferredSize(new java.awt.Dimension(386, 637));
        field_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 159, 103));
        jLabel10.setText("SDT");
        field_5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_5.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 20));

        field_9.setBackground(new java.awt.Color(250, 250, 250));
        field_9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_9.setForeground(new java.awt.Color(250, 250, 250));
        field_9.setPreferredSize(new java.awt.Dimension(386, 637));
        field_9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(14, 159, 103));
        jLabel14.setText("Địa chỉ");
        field_9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        txt_diachi.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_9.add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 20));

        field_14.setBackground(new java.awt.Color(255, 255, 255));
        field_14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_14.setForeground(new java.awt.Color(250, 250, 250));
        field_14.setPreferredSize(new java.awt.Dimension(386, 637));
        field_14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(14, 159, 103));
        jLabel19.setText("Email");
        field_14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_14.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 20));

        field_17.setBackground(new java.awt.Color(255, 255, 255));
        field_17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_17.setForeground(new java.awt.Color(250, 250, 250));
        field_17.setPreferredSize(new java.awt.Dimension(386, 637));
        field_17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tk.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_17.add(txt_tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(14, 159, 103));
        jLabel24.setText("Tên tài khoản");
        field_17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, -1));

        section_2_tab_2.add(field_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 360, 20));

        field_10.setBackground(new java.awt.Color(250, 250, 250));
        field_10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_10.setForeground(new java.awt.Color(250, 250, 250));
        field_10.setPreferredSize(new java.awt.Dimension(386, 637));
        field_10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(14, 159, 103));
        jLabel22.setText("Ngày sinh");
        field_10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, -1));

        txt_ngaySinh.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngaySinhActionPerformed(evt);
            }
        });
        field_10.add(txt_ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 360, 20));

        field_21.setBackground(new java.awt.Color(255, 255, 255));
        field_21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_21.setForeground(new java.awt.Color(250, 250, 250));
        field_21.setPreferredSize(new java.awt.Dimension(386, 637));
        field_21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(14, 159, 103));
        jLabel26.setText("Mật khẩu");
        field_21.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, -1));

        txt_mk.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_21.add(txt_mk, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 360, 20));

        field_8.setBackground(new java.awt.Color(255, 255, 255));
        field_8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_8.setForeground(new java.awt.Color(250, 250, 250));
        field_8.setPreferredSize(new java.awt.Dimension(386, 637));
        field_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(14, 159, 103));
        jLabel13.setText("Giới tính");
        field_8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 100, 11));

        buttonGroup1.add(rdo_nam);
        rdo_nam.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_nam.setText("nam");
        field_8.add(rdo_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, -1, 17));

        buttonGroup1.add(rdo_nu);
        rdo_nu.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_nu.setText("nữ");
        field_8.add(rdo_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1, 90, 17));

        section_2_tab_2.add(field_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 20));

        section_2_tab_1.add(section_2_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 30, 360, 394));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thông tin");
        section_2_tab_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, 15));

        section_2_tab_3.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(146, 23, 21));
        btn_xoa.setText("Ngừng hoạt động");
        btn_xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 23, 21), 2));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 333, 16));

        btn_them.setBackground(new java.awt.Color(14, 159, 103));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 333, 16));

        btn_sua.setBackground(new java.awt.Color(14, 159, 103));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 333, 16));

        section_2_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 440, 360, 180));

        section_2.addTab("Chi tiết", section_2_tab_1);

        jPanel1.add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, -5, 386, 672));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanvienMouseClicked
        index = tbl_nhanvien.getSelectedRow();
        edit();
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_nhanvienMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
           
        delete();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed

        create();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed

        update();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_suaActionPerformed

    private void tbl_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_nvMouseClicked

    private void btn_timkiemnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemnvMouseClicked
        // TODO add your handling code here:
        txt_name_rieng.setVisible(true);
       int result = JOptionPane.showConfirmDialog(this,jPanel2, "Tìm kiếm nhân viên",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    if (result == JOptionPane.OK_OPTION) {
        String name = txt_name_rieng.getText().trim();
        String gender;
        if (rdo_nam_rienh.isSelected()) gender = "Nam";
        else if (rdo_nu_rieng.isSelected()) gender = "Nữ";
        else gender = "all";

        model.setRowCount(0);

        for (NhanVien x : repoNV.findByName(name, gender)) {
            model.addRow(new Object[]{
                x.getId_nhan_vien(),
                x.getMa_nhan_vien(),
                x.getTen_nhan_vien(),
                x.getCccd(),
                x.getEmail(),
                x.getSo_dien_thoai(),
                x.getGioi_tinh(),
                x.getDia_chi()
            });
        }
    }
    }//GEN-LAST:event_btn_timkiemnvMouseClicked

    private void btn_timkiemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemnvActionPerformed

    private void rdo_nam_rienhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nam_rienhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_nam_rienhActionPerformed

    private void txt_name_riengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name_riengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_name_riengActionPerformed

    private void txt_ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngaySinhActionPerformed

    private void rdo_nu_riengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nu_riengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_nu_riengActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar_search;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiemnv;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel field_1;
    private javax.swing.JPanel field_10;
    private javax.swing.JPanel field_14;
    private javax.swing.JPanel field_17;
    private javax.swing.JPanel field_2;
    private javax.swing.JPanel field_21;
    private javax.swing.JPanel field_3;
    private javax.swing.JPanel field_5;
    private javax.swing.JPanel field_8;
    private javax.swing.JPanel field_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdo_all_rieng;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nam_rienh;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JRadioButton rdo_nu_rieng;
    private javax.swing.ButtonGroup rdo_tk;
    private javax.swing.JTabbedPane section_1;
    private javax.swing.JPanel section_1_tab_1;
    private javax.swing.JTabbedPane section_2;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_2;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JTable tbl_nhanvien;
    private javax.swing.JScrollPane tbl_nv;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_mk;
    private javax.swing.JTextField txt_name_rieng;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tk;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(NhanVien entity) {
 throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public NhanVien getForm() {
        NhanVien nv = new NhanVien();

    nv.setMa_nhan_vien(txt_ma.getText());
    nv.setTen_nhan_vien(txt_ten.getText());
    nv.setCccd(txt_cccd.getText());
    nv.setEmail(txt_email.getText());
    nv.setSo_dien_thoai(txt_sdt.getText());
    nv.setDia_chi(txt_diachi.getText());
    nv.setGioi_tinh(rdo_nam.isSelected() ? "Nam" : "Nữ");
    String ngay = txt_ngaySinh.getText().trim();
    Timestamp ngaySinh = null;

    try {
        LocalDate ld = LocalDate.parse(ngay);
        ngaySinh = Timestamp.valueOf(ld.atStartOfDay());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ! Định dạng: yyyy-MM-dd");
    }
    nv.setNgay_sinh(ngaySinh);
    nv.setTai_khoan(txt_tk.getText());
    nv.setMat_khau(txt_mk.getText());

    return nv;
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
    model = (DefaultTableModel) tbl_nhanvien.getModel();
    model.setRowCount(0);

    for (NhanVien nv : repoNV.findAll()) {
        model.addRow(new Object[]{
            nv.getId_nhan_vien(),
            nv.getMa_nhan_vien(),
            nv.getTen_nhan_vien(),
            nv.getCccd(),
            nv.getEmail(),
            nv.getSo_dien_thoai(),
            nv.getGioi_tinh(),
            nv.getDia_chi(),
            nv.getNgay_sinh()
        });
    }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToCbo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void edit() {
          int row = tbl_nhanvien.getSelectedRow();
          int id = Integer.parseInt(tbl_nhanvien.getValueAt(row, 0).toString());
          
          NhanVien x = repoNV.findById(id);
          txt_ma.setText(x.getMa_nhan_vien());
          txt_ten.setText(x.getTen_nhan_vien());
          txt_cccd.setText(x.getCccd());
          txt_email.setText(x.getEmail());
          txt_sdt.setText(x.getSo_dien_thoai());
        if (x.getGioi_tinh() != null && x.getGioi_tinh().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }
        if (x.getNgay_sinh() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            txt_ngaySinh.setText(sdf.format(x.getNgay_sinh()));
        } else {
            txt_ngaySinh.setText("");
        }
          txt_diachi.setText(x.getDia_chi());
          txt_tk.setText(x.getTai_khoan());
          txt_mk.setText(x.getMat_khau());
          
    }
          
    
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

    
    private boolean isValidEmail(String email) {
    return email.matches("^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,}$");
}
    
    
    private boolean isValidPhone(String sdt) {
    return sdt.matches("^\\d{10}$");
}
    
    
    
    
    @Override
    public void create() {
  NhanVien nv = getForm();

  // CHECK EMAIL HỢP LỆ
if (!isValidEmail(nv.getEmail())) {
    JOptionPane.showMessageDialog(this, "Email không hợp lệ! Email phải chứa @ và đúng định dạng.");
    return;
}

// CHECK SĐT HỢP LỆ
if (!isValidPhone(nv.getSo_dien_thoai())) {
    JOptionPane.showMessageDialog(this, "Số điện thoại phải gồm đúng 10 số!");
    return;
}

    if (repoNV.existsMa(nv.getMa_nhan_vien())) {
    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại!");
    return;
}

if (repoNV.existsTaiKhoan(nv.getTai_khoan())) {
    JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!");
    return;
}

if (repoNV.existsCCCD(nv.getCccd())) {
    JOptionPane.showMessageDialog(this, "CCCD đã tồn tại!");
    return;
}

if (repoNV.existsEmail(nv.getEmail())) {
    JOptionPane.showMessageDialog(this, "Email đã tồn tại!");
    return;
}

if (repoNV.existsSdt(nv.getSo_dien_thoai())) {
    JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại!");
    return;
}

    try {
        repoNV.create(nv);
        fillToTable();
        JOptionPane.showMessageDialog(this, " Thêm thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, " Lỗi thêm!");
    }

      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update() {
         int row = tbl_nhanvien.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
        return;
    }

    int id = Integer.parseInt(tbl_nhanvien.getValueAt(row, 0).toString());
    NhanVien old = repoNV.findById(id);     // thông tin cũ
    NhanVien nv = getForm();                // thông tin mới

    // ================= CHECK TRÙNG ================= //

    // 1. Nếu sửa tài khoản
    if (!nv.getTai_khoan().equals(old.getTai_khoan())) {
        if (repoNV.existsTaiKhoan(nv.getTai_khoan())) {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!");
            return;
        }
    }

    // 2. Nếu sửa CCCD
    if (!nv.getCccd().equals(old.getCccd())) {
        if (repoNV.existsCCCD(nv.getCccd())) {
            JOptionPane.showMessageDialog(this, "CCCD đã tồn tại!");
            return;
        }
    }

    // 3. Nếu sửa email
    if (!nv.getEmail().equals(old.getEmail())) {
        if (repoNV.existsEmail(nv.getEmail())) {
            JOptionPane.showMessageDialog(this, "Email đã tồn tại!");
            return;
        }
    }

    // 4. Nếu sửa SDT
    if (!nv.getSo_dien_thoai().equals(old.getSo_dien_thoai())) {
        if (repoNV.existsSdt(nv.getSo_dien_thoai())) {
            JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại!");
            return;
        }
    }

    // 5. Nếu sửa mã nhân viên
    if (!nv.getMa_nhan_vien().equals(old.getMa_nhan_vien())) {
        if (repoNV.existsMa(nv.getMa_nhan_vien())) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại!");
            return;
        }
    }


    try {
        repoNV.update(nv);      // update theo ma_nhan_vien
        fillToTable();
        JOptionPane.showMessageDialog(this, "Sửa thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi sửa: " + e.getMessage());
    }
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
          try {
        int row = tbl_nhanvien.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xoá!");
            return;
        }

        // LẤY ID ĐÚNG Ở CỘT 0
        int id = Integer.parseInt(tbl_nhanvien.getValueAt(row, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá?");
        if (confirm != JOptionPane.YES_OPTION) return;

        repoNV.deleteById(id);  // XOÁ THEO ID

        fillToTable();
        JOptionPane.showMessageDialog(this, "Xoá thành công!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi xoá: " + e.getMessage());
    }
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<NhanVien> findString(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<NhanVien> filterCategory(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
