/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author DELL
 */
public class Pnl_Template extends javax.swing.JPanel {

    /**
     * Creates new form panel_1_sanPhamA
     */
    public Pnl_Template() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        section_1 = new javax.swing.JTabbedPane();
        section_1_tab_1 = new javax.swing.JPanel();
        bar_search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_obj = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        section_2 = new javax.swing.JTabbedPane();
        section_2_tab_1 = new javax.swing.JPanel();
        section_2_tab_2 = new javax.swing.JPanel();
        field_1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        field_2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        field_3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        field_4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        field_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        section_2_tab_3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_1.setToolTipText("tab");

        section_1_tab_1.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_1.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar_search.setBackground(new java.awt.Color(38, 159, 114));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tìm kiếm sản phẩm");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout bar_searchLayout = new javax.swing.GroupLayout(bar_search);
        bar_search.setLayout(bar_searchLayout);
        bar_searchLayout.setHorizontalGroup(
            bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bar_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bar_searchLayout.setVerticalGroup(
            bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bar_searchLayout.createSequentialGroup()
                .addGroup(bar_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        section_1_tab_1.add(bar_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, 290, 20));

        tbl_obj.setForeground(new java.awt.Color(239, 244, 242));
        tbl_obj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_obj);

        section_1_tab_1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 587, 560));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("DANH SÁCH SẢN PHẨM");
        section_1_tab_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        section_1.addTab("Thông tin chi tiết", section_1_tab_1);

        add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, -5, 613, 672));

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_2.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_2.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_1.setBackground(new java.awt.Color(250, 250, 250));
        field_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_1.setForeground(new java.awt.Color(250, 250, 250));
        field_1.setPreferredSize(new java.awt.Dimension(386, 637));
        field_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 159, 103));
        jLabel6.setText("Mã sản phẩm:");
        field_1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jTextField2.setText("jTextField2");
        field_1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 20));

        field_2.setBackground(new java.awt.Color(255, 255, 255));
        field_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_2.setForeground(new java.awt.Color(250, 250, 250));
        field_2.setPreferredSize(new java.awt.Dimension(386, 637));
        field_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 159, 103));
        jLabel7.setText("Tên sản phẩm");
        field_2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jTextField3.setText("jTextField2");
        field_2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 20));

        field_3.setBackground(new java.awt.Color(250, 250, 250));
        field_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_3.setForeground(new java.awt.Color(250, 250, 250));
        field_3.setPreferredSize(new java.awt.Dimension(386, 637));
        field_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 159, 103));
        jLabel8.setText("Loại sản phẩm:");
        field_3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        field_3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 20));

        field_4.setBackground(new java.awt.Color(255, 255, 255));
        field_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_4.setForeground(new java.awt.Color(250, 250, 250));
        field_4.setPreferredSize(new java.awt.Dimension(386, 637));
        field_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(14, 159, 103));
        jLabel9.setText("Loại thuộc tính:");
        field_4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        field_4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jRadioButton2.setText("jRadioButton1");
        field_4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 19, 240, 17));

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jRadioButton3.setText("jRadioButton1");
        field_4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 38, 240, 17));

        section_2_tab_2.add(field_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 60));

        field_5.setBackground(new java.awt.Color(250, 250, 250));
        field_5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_5.setForeground(new java.awt.Color(250, 250, 250));
        field_5.setPreferredSize(new java.awt.Dimension(386, 637));
        field_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 159, 103));
        jLabel10.setText("...");
        field_5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jTextField4.setText("jTextField2");
        field_5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 20));

        section_2_tab_1.add(section_2_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, 360, 394));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thông tin");
        section_2_tab_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, 15));

        section_2_tab_3.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(14, 159, 103));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("jButton10");
        section_2_tab_3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, 333, 16));

        section_2_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 442, 360, 180));

        section_2.addTab("Chi tiết", section_2_tab_1);

        add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, -5, 386, 672));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar_search;
    private javax.swing.JPanel field_1;
    private javax.swing.JPanel field_2;
    private javax.swing.JPanel field_3;
    private javax.swing.JPanel field_4;
    private javax.swing.JPanel field_5;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTabbedPane section_1;
    private javax.swing.JPanel section_1_tab_1;
    private javax.swing.JTabbedPane section_2;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_2;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JTable tbl_obj;
    // End of variables declaration//GEN-END:variables
}
