/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.formdev.flatlaf.FlatLightLaf;
import dao.Dao_DangNhap;
import daoipml.DaoImpl_DangNhap;
import entity.NhanVien;
import javax.swing.*;
import java.net.URL;

/**
 *
 * @author PC
 */
public class pnl_DangNhap extends javax.swing.JFrame {
    public static int idNV = -1;
    public static String maVT = "";
    public static String tenNV = "";
    /**
     * Creates new form pnl_DangNhap
     */
    public pnl_DangNhap() {
        // init ui theme        
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        initComponents();
        this.loadIcon(icon_logo,"/images/logo_login_1.png");

        
    }

private void loadIcon(JLabel label,String iconPath){
    // Correct way to load image from resources
        URL imageURL = getClass().getResource(iconPath);
        if (imageURL != null) {
            ImageIcon icon = new ImageIcon(imageURL);
            label.setIcon(icon);
            System.err.println("Image found: "+iconPath);
        } else {
            System.err.println("Image not found: "+iconPath);
        }
}

private void dangNhap() {

    String taiKhoan = txt_taikhoan.getText().trim();
    String matKhau = txt_matkhau.getText().trim();

    if (taiKhoan.isEmpty() || matKhau.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không được để trống!");
        return;
    }

    Dao_DangNhap dao = new DaoImpl_DangNhap();
    NhanVien nv = dao.login(taiKhoan, matKhau);

    if (nv == null) {
        JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu!");
        return;
    }
     idNV = nv.getId_nhan_vien();
     maVT= nv.getMa_vai_tro();
     tenNV = nv.getTen_nhan_vien();
    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");

    Form_Home home = new Form_Home();
    home.setVisible(true);

    this.dispose();
}   


    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        section_2_tab_1 = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        section_2_tab_3 = new javax.swing.JPanel();
        btn_thoat = new javax.swing.JButton();
        btn_dangnhap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_taikhoan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_matkhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(250, 320));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        section_2_tab_1.add(icon_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, 200, 200));

        getContentPane().add(section_2_tab_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        section_2_tab_3.setBackground(new java.awt.Color(235, 249, 245));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(250, 320));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(146, 23, 21));
        btn_thoat.setText("Thoát");
        btn_thoat.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(146, 23, 21)));
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, 20));

        btn_dangnhap.setBackground(new java.awt.Color(14, 159, 103));
        btn_dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangnhap.setText("Đăng nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 159, 105));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ĐĂNG NHẬP");
        section_2_tab_3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, 210, 22));

        txt_taikhoan.setBackground(new java.awt.Color(247, 255, 253));
        txt_taikhoan.setForeground(new java.awt.Color(14, 159, 103));
        txt_taikhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(14, 159, 103)));
        section_2_tab_3.add(txt_taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 118, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 159, 103));
        jLabel1.setText("Tài khoản");
        section_2_tab_3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 159, 103));
        jLabel2.setText("Mật khẩu");
        section_2_tab_3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 154, -1, -1));

        txt_matkhau.setBackground(new java.awt.Color(247, 255, 253));
        txt_matkhau.setForeground(new java.awt.Color(14, 159, 103));
        txt_matkhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(14, 159, 103)));
        txt_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matkhauActionPerformed(evt);
            }
        });
        section_2_tab_3.add(txt_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 154, 130, -1));

        getContentPane().add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
    dangNhap();        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void txt_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matkhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pnl_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pnl_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pnl_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pnl_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnl_DangNhap().setVisible(true);
            }
        });
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JTextField txt_taikhoan;
    // End of variables declaration//GEN-END:variables
}
