/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import com.formdev.flatlaf.FlatLightLaf;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import controller.Controller_PhieuGiamGia;
import daoipml.DaoImpl_PhieuGiamGia;
import entity.PhieuGiamGia;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Pnl_8_PhieuGiamGia extends javax.swing.JPanel implements Controller_PhieuGiamGia{
    DatePickerSettings settings = new DatePickerSettings();
    DatePicker datePickerStart = new DatePicker();
    DatePicker datePickerEnd = new DatePicker();
    DaoImpl_PhieuGiamGia repoPGG= new DaoImpl_PhieuGiamGia();
    DefaultTableModel model = new DefaultTableModel();
    private int index = -1;
    /**
     * Creates new form panel_1_sanPhamA
     */
    public Pnl_8_PhieuGiamGia() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        initComponents();
        repoPGG.capNhatTrangThai();
        this.fillToCbo();
        this.fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgr_tt = new javax.swing.ButtonGroup();
        section_1_tab_2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bar_search1 = new javax.swing.JPanel();
        txt_timkiemPGG = new javax.swing.JTextField();
        btn_timkiemPGG = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_phieuGG = new javax.swing.JTable();
        section_2_tab_1 = new javax.swing.JPanel();
        section_2_tab_3 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        section_2_tab_4 = new javax.swing.JPanel();
        field_6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        field_7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        field_8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbo_loaiGiamGia = new javax.swing.JComboBox<>();
        field_12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        rdo_HD = new javax.swing.JRadioButton();
        rdo_khongHD = new javax.swing.JRadioButton();
        field_21 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txt_giamToiDa = new javax.swing.JTextField();
        field_23 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        date_PickerStart = new com.github.lgooddatepicker.components.DatePicker();
        field_20 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txt_donToiThieu = new javax.swing.JTextField();
        field_22 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        field_24 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        date_PickerEnd = new com.github.lgooddatepicker.components.DatePicker();
        field_11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_mucGiam = new javax.swing.JTextField();

        setBackground(new java.awt.Color(235, 249, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_1_tab_2.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_2.setForeground(new java.awt.Color(6, 71, 46));
        section_1_tab_2.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 71, 46));
        jLabel4.setText("Danh sách ưu đãi");
        section_1_tab_2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        bar_search1.setBackground(new java.awt.Color(38, 159, 114));
        bar_search1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_timkiemPGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemPGGActionPerformed(evt);
            }
        });
        bar_search1.add(txt_timkiemPGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3, 142, 18));

        btn_timkiemPGG.setText("Tìm sản phẩm");
        btn_timkiemPGG.setBackground(new java.awt.Color(38, 159, 114));
        btn_timkiemPGG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiemPGG.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemPGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemPGGMouseClicked(evt);
            }
        });
        btn_timkiemPGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemPGGActionPerformed(evt);
            }
        });
        bar_search1.add(btn_timkiemPGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 3, 128, 18));

        section_1_tab_2.add(bar_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, 290, 24));

        jScrollPane3.setBackground(new java.awt.Color(38, 159, 114));
        jScrollPane3.setForeground(new java.awt.Color(6, 71, 46));

        tbl_phieuGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu", "Tên", "Loại", "Mức giảm %", "Đơn tối thiểu", "Giảm tối đa", "Số lượng", "Bắt đầu", "Kết thúc", "TT"
            }
        ));
        tbl_phieuGG.setForeground(new java.awt.Color(6, 71, 46));
        tbl_phieuGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_phieuGGMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_phieuGG);
        if (tbl_phieuGG.getColumnModel().getColumnCount() > 0) {
            tbl_phieuGG.getColumnModel().getColumn(0).setPreferredWidth(32);
        }

        section_1_tab_2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 587, 407));

        add(section_1_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 613, 457));

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_3.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_them.setText("Thêm");
        btn_them.setBackground(new java.awt.Color(14, 159, 103));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, 333, 16));

        btn_sua.setText("Sửa");
        btn_sua.setBackground(new java.awt.Color(14, 159, 103));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 36, 333, 16));

        btn_lammoi.setText("Làm mới");
        btn_lammoi.setBackground(new java.awt.Color(14, 159, 103));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 59, 333, 16));

        btn_xoa.setText("Xóa");
        btn_xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 23, 21), 2));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(146, 23, 21));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 82, 333, 16));

        section_2_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 442, 360, 180));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Thông tin ưu đãi");
        section_2_tab_1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 15));

        section_2_tab_4.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_4.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_4.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_6.setBackground(new java.awt.Color(255, 255, 255));
        field_6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_6.setForeground(new java.awt.Color(250, 250, 250));
        field_6.setPreferredSize(new java.awt.Dimension(386, 637));
        field_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(14, 159, 103));
        jLabel12.setText("Mã phiếu:");
        field_6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 11));

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_ma.setForeground(new java.awt.Color(6, 71, 46));
        field_6.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 20));

        field_7.setBackground(new java.awt.Color(250, 250, 250));
        field_7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_7.setForeground(new java.awt.Color(250, 250, 250));
        field_7.setPreferredSize(new java.awt.Dimension(386, 637));
        field_7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(14, 159, 103));
        jLabel13.setText("Tên phiếu:");
        field_7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_ten.setForeground(new java.awt.Color(6, 71, 46));
        field_7.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 20));

        field_8.setBackground(new java.awt.Color(255, 255, 255));
        field_8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_8.setForeground(new java.awt.Color(250, 250, 250));
        field_8.setPreferredSize(new java.awt.Dimension(386, 637));
        field_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(14, 159, 103));
        jLabel14.setText("loại giảm giá:");
        field_8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        cbo_loaiGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_loaiGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        cbo_loaiGiamGia.setForeground(new java.awt.Color(6, 71, 46));
        field_8.add(cbo_loaiGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 20));

        field_12.setBackground(new java.awt.Color(250, 250, 250));
        field_12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_12.setForeground(new java.awt.Color(250, 250, 250));
        field_12.setPreferredSize(new java.awt.Dimension(386, 637));
        field_12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(14, 159, 103));
        jLabel19.setText("Trạng thái:");
        field_12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        btgr_tt.add(rdo_HD);
        rdo_HD.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_HD.setText("Hoạt động");
        field_12.add(rdo_HD, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 100, 17));

        btgr_tt.add(rdo_khongHD);
        rdo_khongHD.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_khongHD.setSelected(true);
        rdo_khongHD.setText("Không hoạt động");
        rdo_khongHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_khongHDActionPerformed(evt);
            }
        });
        field_12.add(rdo_khongHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 17));

        section_2_tab_4.add(field_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 360, 20));

        field_21.setBackground(new java.awt.Color(250, 250, 250));
        field_21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_21.setForeground(new java.awt.Color(250, 250, 250));
        field_21.setPreferredSize(new java.awt.Dimension(386, 637));
        field_21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(14, 159, 103));
        jLabel32.setText("Giảm tối đa:");
        field_21.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_giamToiDa.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_giamToiDa.setForeground(new java.awt.Color(6, 71, 46));
        field_21.add(txt_giamToiDa, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 20));

        field_23.setBackground(new java.awt.Color(250, 250, 250));
        field_23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_23.setForeground(new java.awt.Color(250, 250, 250));
        field_23.setPreferredSize(new java.awt.Dimension(386, 637));
        field_23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(14, 159, 103));
        jLabel34.setText("Thời gian bắt đầu:");
        field_23.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));
        field_23.add(date_PickerStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 250, -1));

        section_2_tab_4.add(field_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 360, 20));

        field_20.setBackground(new java.awt.Color(255, 255, 255));
        field_20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_20.setForeground(new java.awt.Color(250, 250, 250));
        field_20.setPreferredSize(new java.awt.Dimension(386, 637));
        field_20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(14, 159, 103));
        jLabel31.setText("Đơn tối thiểu:");
        field_20.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_donToiThieu.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_donToiThieu.setForeground(new java.awt.Color(6, 71, 46));
        field_20.add(txt_donToiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 20));

        field_22.setBackground(new java.awt.Color(255, 255, 255));
        field_22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_22.setForeground(new java.awt.Color(250, 250, 250));
        field_22.setPreferredSize(new java.awt.Dimension(386, 637));
        field_22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(14, 159, 103));
        jLabel33.setText("Số lượng:");
        field_22.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_soLuong.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_soLuong.setForeground(new java.awt.Color(6, 71, 46));
        field_22.add(txt_soLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 20));

        field_24.setBackground(new java.awt.Color(255, 255, 255));
        field_24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_24.setForeground(new java.awt.Color(250, 250, 250));
        field_24.setPreferredSize(new java.awt.Dimension(386, 637));
        field_24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(14, 159, 103));
        jLabel35.setText("Thời gian kết thúc:");
        field_24.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));
        field_24.add(date_PickerEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 250, -1));

        section_2_tab_4.add(field_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 360, 20));

        field_11.setBackground(new java.awt.Color(250, 250, 250));
        field_11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_11.setForeground(new java.awt.Color(250, 250, 250));
        field_11.setPreferredSize(new java.awt.Dimension(386, 637));
        field_11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(14, 159, 103));
        jLabel17.setText("Mức giảm(%):");
        field_11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_mucGiam.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_mucGiam.setForeground(new java.awt.Color(6, 71, 46));
        field_11.add(txt_mucGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_4.add(field_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 20));

        section_2_tab_1.add(section_2_tab_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, 322));

        add(section_2_tab_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_timkiemPGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemPGGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemPGGActionPerformed

    private void btn_timkiemPGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemPGGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemPGGMouseClicked

    private void btn_timkiemPGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemPGGActionPerformed
        // TODO add your handling code here:
        String name = txt_timkiemPGG.getText();
        model.setRowCount(0);
        for (PhieuGiamGia gg : repoPGG.findByName(name)) {
        model.addRow(new Object[]{
            gg.getId_phieu_giam_gia(),
            gg.getMa_phieu_giam(),
            gg.getTen_phieu_giam(),
            gg.getLoai_giam_gia()==0 ?"Giảm theo %":"Giảm theo số tiền",
            gg.getGia_tri_giam(),
            gg.getDon_toi_thieu(),
            gg.getGiam_toi_da(),
            gg.getSo_luong(),
            gg.getThoi_gian_bat_dau(),
            gg.getThoi_gian_ket_thuc(),
            gg.isTrang_thai()
        });
        }
    }//GEN-LAST:event_btn_timkiemPGGActionPerformed

    private void rdo_khongHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_khongHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_khongHDActionPerformed

    private void tbl_phieuGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_phieuGGMouseClicked
        // TODO add your handling code here:
        index = tbl_phieuGG.getSelectedRow();
        this.edit();
    }//GEN-LAST:event_tbl_phieuGGMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        this.create();
    }//GEN-LAST:event_btn_themActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar_search1;
    private javax.swing.ButtonGroup btgr_tt;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiemPGG;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_loaiGiamGia;
    private com.github.lgooddatepicker.components.DatePicker date_PickerEnd;
    private com.github.lgooddatepicker.components.DatePicker date_PickerStart;
    private javax.swing.JPanel field_11;
    private javax.swing.JPanel field_12;
    private javax.swing.JPanel field_20;
    private javax.swing.JPanel field_21;
    private javax.swing.JPanel field_22;
    private javax.swing.JPanel field_23;
    private javax.swing.JPanel field_24;
    private javax.swing.JPanel field_6;
    private javax.swing.JPanel field_7;
    private javax.swing.JPanel field_8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdo_HD;
    private javax.swing.JRadioButton rdo_khongHD;
    private javax.swing.JPanel section_1_tab_2;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JPanel section_2_tab_4;
    private javax.swing.JTable tbl_phieuGG;
    private javax.swing.JTextField txt_donToiThieu;
    private javax.swing.JTextField txt_giamToiDa;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_mucGiam;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiemPGG;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
    }

    @Override
    public void setForm(PhieuGiamGia entity) {
    }

    @Override
    public PhieuGiamGia getForm() {
        PhieuGiamGia pgg = new PhieuGiamGia();
        pgg.setMa_phieu_giam(txt_ma.getText());
        pgg.setTen_phieu_giam(txt_ten.getText());
        int loai = cbo_loaiGiamGia.getSelectedIndex();
        pgg.setLoai_giam_gia(loai);
        pgg.setGia_tri_giam(new BigDecimal(txt_mucGiam.getText()));
        pgg.setDon_toi_thieu(new BigDecimal(txt_donToiThieu.getText()));
        pgg.setGiam_toi_da(new BigDecimal(txt_giamToiDa.getText()));
        pgg.setSo_luong(Integer.parseInt(txt_soLuong.getText()));
        if (date_PickerStart.getDate() !=null) {
            pgg.setThoi_gian_bat_dau(
            Timestamp.valueOf(date_PickerStart.getDate().atStartOfDay()));
        }
        if (date_PickerEnd.getDate() !=null) {
            pgg.setThoi_gian_ket_thuc(
            Timestamp.valueOf(date_PickerEnd.getDate().atStartOfDay()));
 
        }
        if (rdo_HD.isSelected()) {
        pgg.setTrang_thai(true);   
        } else {
            pgg.setTrang_thai(false); 
        }
        return pgg;
    }

    @Override
    public void fillToTable() {
        model = (DefaultTableModel) tbl_phieuGG.getModel();
        model.setRowCount(0);
        
        repoPGG.capNhatTrangThai();

        for (PhieuGiamGia gg : repoPGG.findAll()) {
        model.addRow(new Object[]{
            gg.getId_phieu_giam_gia(),
            gg.getMa_phieu_giam(),
            gg.getTen_phieu_giam(),
            gg.getLoai_giam_gia()==0 ?"Giảm theo %":"Giảm theo số tiền",
            gg.getGia_tri_giam(),
            gg.getDon_toi_thieu(),
            gg.getGiam_toi_da(),
            gg.getSo_luong(),
            gg.getThoi_gian_bat_dau(),
            gg.getThoi_gian_ket_thuc(),
            gg.isTrang_thai()? "Hoạt động" : "Không hoạt động" 
        });
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    }

    @Override
    public void fillToCbo() {
        cbo_loaiGiamGia.removeAllItems();
        cbo_loaiGiamGia.addItem("Giảm theo %");        // value = 0
        cbo_loaiGiamGia.addItem("Giảm theo số tiền"); 
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void edit() {
    int row = tbl_phieuGG.getSelectedRow();

    int id = (int) tbl_phieuGG.getValueAt(row, 0);

    PhieuGiamGia x = repoPGG.findById(id);

    txt_ma.setText(x.getMa_phieu_giam());
    txt_ten.setText(x.getTen_phieu_giam());

    if (x.getLoai_giam_gia() == 0) {
        cbo_loaiGiamGia.setSelectedItem("Giảm theo %");
    } else {
        cbo_loaiGiamGia.setSelectedItem("Giảm theo số tiền");
    }

    txt_mucGiam.setText(String.valueOf(x.getGia_tri_giam()));
    txt_donToiThieu.setText(String.valueOf(x.getDon_toi_thieu()));
    txt_giamToiDa.setText(String.valueOf(x.getGiam_toi_da()));
    txt_soLuong.setText(String.valueOf(x.getSo_luong()));

    if (x.getThoi_gian_bat_dau() != null) {
        LocalDate start = x.getThoi_gian_bat_dau().toLocalDateTime().toLocalDate();
        date_PickerStart.setDate(start);
    }

    if (x.getThoi_gian_ket_thuc() != null) {
        LocalDate end = x.getThoi_gian_ket_thuc().toLocalDateTime().toLocalDate();
        date_PickerEnd.setDate(end);
    }


    if (x.isTrang_thai()) {
        rdo_HD.setSelected(true);
    } else {
        rdo_khongHD.setSelected(true);
    }
}
    
    
    private boolean validateDuplicate() {
    String ma = txt_ma.getText().trim();
    String ten = txt_ten.getText().trim();

    if (repoPGG.existsMa(ma)) {
        JOptionPane.showMessageDialog(this, "Mã phiếu đã tồn tại!");
        return false;
    }
    if (repoPGG.existsTen(ten)) {
        JOptionPane.showMessageDialog(this, "Tên phiếu đã tồn tại!");
        return false;
    }
    return true;
}
    
    
    

    @Override
    public void create() {
        if (!validateDuplicate()) return; // nếu trùng thì dừng ngay
        
    try {
        repoPGG.create(getForm());
        fillToTable();
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi thêm!");
    }
    }
    
    
    
    private boolean validateDuplicateUpdate(int id) {
    String ma = txt_ma.getText().trim();
    String ten = txt_ten.getText().trim();

    PhieuGiamGia old = repoPGG.findById(id);

    if (!ma.equals(old.getMa_phieu_giam()) && repoPGG.existsMa(ma)) {
        JOptionPane.showMessageDialog(this, "Mã phiếu đã tồn tại!");
        return false;
    }
    if (!ten.equals(old.getTen_phieu_giam()) && repoPGG.existsTen(ten)) {
        JOptionPane.showMessageDialog(this, "Tên phiếu đã tồn tại!");
        return false;
    }
    return true;
}
    
    
    

    @Override
    public void update() {
    int row = tbl_phieuGG.getSelectedRow();
    int id = Integer.parseInt(tbl_phieuGG.getValueAt(row, 0).toString());

    if (!validateDuplicateUpdate(id)) return;
        
    try {
        repoPGG.update(getForm());
        fillToTable();
        JOptionPane.showMessageDialog(this, "Sửa thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi sửa!");
    }
    }

    @Override
    public void delete() {
        int row = tbl_phieuGG.getSelectedRow();
        int id = Integer.parseInt(tbl_phieuGG.getValueAt(row, 0).toString());
        repoPGG.deleteById(id);
        this.fillToTable();
        JOptionPane.showMessageDialog(this, "Xoá thành công!");
    }

    @Override
    public List<PhieuGiamGia> findString(String key) {
        return null;
    }

    @Override
    public List<PhieuGiamGia> filterCategory(String key) {
        return null;
    }

    @Override
    public void clear() {
    }

    @Override
    public void setEditable(boolean editable) {
    }

    @Override
    public void checkAll() {
    }

    @Override
    public void uncheckAll() {
    }

    @Override
    public void deleteCheckedItems() {
    }

    @Override
    public void moveFirst() {
    }

    @Override
    public void moveTo(int rowIndex) {
    }
     public void formatDate() {
        DatePickerSettings settings = new DatePickerSettings();
        settings.setFormatForDatesCommonEra("yyyy-MM-dd");

//        settings.setMonthFormatter(month -> String.format("%02d", month.getValue()));// Month dropdown show as numbers (01-12)
        DatePicker datePicker = new DatePicker(settings);
        date_PickerStart.add(datePicker);
        date_PickerEnd.add(datePicker);

 }

    @Override
    public void movePrevious() {
    }

    @Override
    public void moveNext() {
    }

    @Override
    public void moveLast() {
    }
}
