/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import com.formdev.flatlaf.FlatLightLaf;
import controller.Controller_KhachHang;
import daoipml.DaoImpl_KhachHang;
import entity.KhachHang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Pnl_5_qlKhachHang extends javax.swing.JPanel implements Controller_KhachHang{
DaoImpl_KhachHang repoKH= new DaoImpl_KhachHang();
DefaultTableModel model = new DefaultTableModel();
private int index = -1;

    /**
     * Creates new form panel_1_sanPhamA
     */
    public Pnl_5_qlKhachHang() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        initComponents();
        phanquyen();
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgr_gt = new javax.swing.ButtonGroup();
        btgr_tt = new javax.swing.ButtonGroup();
        section_1 = new javax.swing.JTabbedPane();
        section_1_tab_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        bar_search = new javax.swing.JPanel();
        txt_timkiemkh = new javax.swing.JTextField();
        btn_timkiemkh = new javax.swing.JButton();
        section_2 = new javax.swing.JTabbedPane();
        section_2_tab_1 = new javax.swing.JPanel();
        section_2_tab_2 = new javax.swing.JPanel();
        field_1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_makh = new javax.swing.JTextField();
        field_2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        field_3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        field_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        field_8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        field_14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        rdo_gtNu = new javax.swing.JRadioButton();
        rdo_gtNam = new javax.swing.JRadioButton();
        field_15 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        rdo_TTdefault = new javax.swing.JRadioButton();
        rdo_TTVip = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        section_2_tab_3 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 249, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_1.setToolTipText("tab");

        section_1_tab_1.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_1.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Tên KH", "Giới tính", "SDT", "Địa chỉ", "Email", "Trạng thái"
            }
        ));
        tbl_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachHang);
        if (tbl_khachHang.getColumnModel().getColumnCount() > 0) {
            tbl_khachHang.getColumnModel().getColumn(0).setPreferredWidth(28);
        }

        section_1_tab_1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 587, 560));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 71, 46));
        jLabel3.setText("DANH SÁCH KHÁCH HÀNG");
        section_1_tab_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        bar_search.setBackground(new java.awt.Color(38, 159, 114));
        bar_search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_timkiemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemkhActionPerformed(evt);
            }
        });
        bar_search.add(txt_timkiemkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3, 142, 18));

        btn_timkiemkh.setBackground(new java.awt.Color(38, 159, 114));
        btn_timkiemkh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiemkh.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemkh.setText("Tìm khách hàng");
        btn_timkiemkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemkhMouseClicked(evt);
            }
        });
        btn_timkiemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemkhActionPerformed(evt);
            }
        });
        bar_search.add(btn_timkiemkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 3, 128, 18));

        section_1_tab_1.add(bar_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, 290, 24));

        section_1.addTab("Thông tin chi tiết", section_1_tab_1);

        add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, -5, 613, 672));

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_2.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_2.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_1.setBackground(new java.awt.Color(250, 250, 250));
        field_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_1.setForeground(new java.awt.Color(250, 250, 250));
        field_1.setPreferredSize(new java.awt.Dimension(386, 637));
        field_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 159, 103));
        jLabel6.setText("Mã Khách Hàng:");
        field_1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_makh.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txt_makh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_makhActionPerformed(evt);
            }
        });
        field_1.add(txt_makh, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 20));

        field_2.setBackground(new java.awt.Color(255, 255, 255));
        field_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_2.setForeground(new java.awt.Color(250, 250, 250));
        field_2.setPreferredSize(new java.awt.Dimension(386, 637));
        field_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 159, 103));
        jLabel7.setText("Tên Khách Hàng");
        field_2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_tenkh.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_2.add(txt_tenkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 20));

        field_3.setBackground(new java.awt.Color(250, 250, 250));
        field_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_3.setForeground(new java.awt.Color(250, 250, 250));
        field_3.setPreferredSize(new java.awt.Dimension(386, 637));
        field_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 159, 103));
        jLabel8.setText("Địa chỉ: ");
        field_3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_diachi.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_3.add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 20));

        field_5.setBackground(new java.awt.Color(255, 255, 255));
        field_5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_5.setForeground(new java.awt.Color(250, 250, 250));
        field_5.setPreferredSize(new java.awt.Dimension(386, 637));
        field_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 159, 103));
        jLabel10.setText("SĐT:");
        field_5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_5.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 20));

        field_8.setBackground(new java.awt.Color(250, 250, 250));
        field_8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_8.setForeground(new java.awt.Color(250, 250, 250));
        field_8.setPreferredSize(new java.awt.Dimension(386, 637));
        field_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(14, 159, 103));
        jLabel13.setText("Email:");
        field_8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_8.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 17));

        section_2_tab_2.add(field_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 20));

        field_14.setBackground(new java.awt.Color(255, 255, 255));
        field_14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_14.setForeground(new java.awt.Color(250, 250, 250));
        field_14.setPreferredSize(new java.awt.Dimension(386, 637));
        field_14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(14, 159, 103));
        jLabel19.setText("Giới tính:");
        field_14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        btgr_gt.add(rdo_gtNu);
        rdo_gtNu.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_gtNu.setText("Nữ");
        rdo_gtNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_gtNuActionPerformed(evt);
            }
        });
        field_14.add(rdo_gtNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 17));

        btgr_gt.add(rdo_gtNam);
        rdo_gtNam.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_gtNam.setText("Nam");
        field_14.add(rdo_gtNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 100, 17));

        section_2_tab_2.add(field_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 20));

        field_15.setBackground(new java.awt.Color(255, 255, 255));
        field_15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_15.setForeground(new java.awt.Color(250, 250, 250));
        field_15.setPreferredSize(new java.awt.Dimension(386, 637));
        field_15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(14, 159, 103));
        jLabel20.setText("Trạng thái:");
        field_15.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        btgr_tt.add(rdo_TTdefault);
        rdo_TTdefault.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_TTdefault.setText("Thường");
        rdo_TTdefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_TTdefaultActionPerformed(evt);
            }
        });
        field_15.add(rdo_TTdefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 100, 17));

        btgr_tt.add(rdo_TTVip);
        rdo_TTVip.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_TTVip.setText("Vip");
        rdo_TTVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_TTVipActionPerformed(evt);
            }
        });
        field_15.add(rdo_TTVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 17));

        section_2_tab_2.add(field_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 20));

        section_2_tab_1.add(section_2_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, 360, 394));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thêm Thông Tin Khách Hàng");
        section_2_tab_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, 15));

        section_2_tab_3.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_add.setBackground(new java.awt.Color(14, 159, 103));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, 333, 16));

        btn_sua.setBackground(new java.awt.Color(14, 159, 103));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, 333, 16));

        btn_lammoi.setBackground(new java.awt.Color(14, 159, 103));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setText("Làm mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 59, 333, 16));

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(146, 23, 21));
        btn_xoa.setText("Xoá");
        btn_xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 23, 21), 2));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 83, 333, 16));

        section_2_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 442, 360, 180));

        section_2.addTab("Chi tiết", section_2_tab_1);

        add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, -5, 386, 672));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
            this.create();
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        this.update();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void txt_timkiemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemkhActionPerformed
        //timTheoMa(txt_timkiemsp.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemkhActionPerformed

    private void btn_timkiemkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemkhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemkhMouseClicked

    private void btn_timkiemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemkhActionPerformed
        // TODO add your handling code here:
        String name = txt_timkiemkh.getText();
        model.setRowCount(0);
        for (KhachHang kh : repoKH.findByName(name)){
        model.addRow(new Object[]{
            kh.getId_khach_hang(),
            kh.getMa_khach_hang(),
            kh.getTen_khach_hang(),
            kh.getGioi_tinh(),
            kh.getSo_dien_thoai(),
            kh.getDia_chi(),
            kh.getEmail(),
            kh.isTrang_thai(),
        });
    }
    }//GEN-LAST:event_btn_timkiemkhActionPerformed

    private void rdo_TTVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_TTVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_TTVipActionPerformed

    private void rdo_gtNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_gtNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_gtNuActionPerformed

    private void txt_makhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_makhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_makhActionPerformed

    private void tbl_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachHangMouseClicked
        // TODO add your handling code here:
        index =tbl_khachHang.getSelectedRow();
        edit();
    }//GEN-LAST:event_tbl_khachHangMouseClicked

    private void rdo_TTdefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_TTdefaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_TTdefaultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar_search;
    private javax.swing.ButtonGroup btgr_gt;
    private javax.swing.ButtonGroup btgr_tt;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_timkiemkh;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JPanel field_1;
    private javax.swing.JPanel field_14;
    private javax.swing.JPanel field_15;
    private javax.swing.JPanel field_2;
    private javax.swing.JPanel field_3;
    private javax.swing.JPanel field_5;
    private javax.swing.JPanel field_8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_TTVip;
    private javax.swing.JRadioButton rdo_TTdefault;
    private javax.swing.JRadioButton rdo_gtNam;
    private javax.swing.JRadioButton rdo_gtNu;
    private javax.swing.JTabbedPane section_1;
    private javax.swing.JPanel section_1_tab_1;
    private javax.swing.JTabbedPane section_2;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_2;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_timkiemkh;
    // End of variables declaration//GEN-END:variables


    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(KhachHang entity) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public KhachHang getForm() {
    KhachHang kh = new KhachHang();
    kh.setMa_khach_hang(txt_makh.getText());
    kh.setTen_khach_hang(txt_tenkh.getText());
    kh.setSo_dien_thoai(txt_sdt.getText());
    kh.setDia_chi(txt_diachi.getText());
    kh.setEmail(txt_email.getText());

    if (rdo_gtNam.isSelected()) {
        kh.setGioi_tinh("Nam");
    } else {
        kh.setGioi_tinh("Nữ");
    }
    if (rdo_TTVip.isSelected()) {
        kh.setTrang_thai(false);   
    } else {
        kh.setTrang_thai(true); 
    }
    return kh;
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
            model = (DefaultTableModel) tbl_khachHang.getModel();
            model.setRowCount(0);

        for (KhachHang kh : repoKH.findAll()) {
        model.addRow(new Object[]{
            kh.getId_khach_hang(),
            kh.getMa_khach_hang(),
            kh.getTen_khach_hang(),
            kh.getGioi_tinh(),
            kh.getSo_dien_thoai(),
            kh.getDia_chi(),
            kh.getEmail(),
            kh.isTrang_thai()==true?"Thường":"Vip"
        });
    }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void clearForm() {

        
    }
    @Override
    public void fillToCbo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void edit() {
          int row = tbl_khachHang.getSelectedRow();
          int id = Integer.parseInt(tbl_khachHang.getValueAt(row, 0).toString());
          
          KhachHang x = repoKH.findById(id);
          txt_makh.setText(x.getMa_khach_hang());
          txt_tenkh.setText(x.getTen_khach_hang());
          String gt = x.getGioi_tinh();
          if (gt.equalsIgnoreCase("Nam")) {
            rdo_gtNam.setSelected(true);
        } else {
            rdo_gtNu.setSelected(true); 
        }
          txt_sdt.setText(x.getSo_dien_thoai());
          txt_diachi.setText(x.getDia_chi());
          txt_email.setText(x.getEmail());
        if (x.isTrang_thai()) {
            rdo_TTdefault.setSelected(true);
        } else {
            rdo_TTVip.setSelected(true);
        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    //valid
    private boolean isValidEmail(String email) {
    return email.matches(".+@.+\\..+");
}


// Kiểm tra SDT phải là đúng 10 số
    private boolean isValidPhone(String sdt) {
    return sdt.matches("\\d{10}");
    }
    @Override
    public void create() {
        KhachHang kh = getForm();
        
        

// kiểm tra email
        if (!isValidEmail(kh.getEmail())) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ phải có @!");
            return;
        }

// kiểm tra số điện thoại
        if (!isValidPhone(kh.getSo_dien_thoai())) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải đúng 10 số!");
            return;
        }

// kiểm tra trùng
        if (repoKH.existsMa(kh.getMa_khach_hang())) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại!");
            return;
        }

        if (repoKH.existsEmail(kh.getEmail())) {
            JOptionPane.showMessageDialog(this, "Email đã tồn tại!");
            return;
        }

        if (repoKH.existsSDT(kh.getSo_dien_thoai())) {
            JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại!");
            return;
        }
        
        try {
        repoKH.create(kh);
        fillToTable();
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi thêm dữ liệu!");
    }

        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update() {
        try {
        repoKH.update(getForm());
        fillToTable();
        JOptionPane.showMessageDialog(this, "Sửa thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi sửa!");
    }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
        int row = tbl_khachHang.getSelectedRow();
        int id = Integer.parseInt(tbl_khachHang.getValueAt(row, 0).toString());
        repoKH.deleteById(id);
        this.fillToTable();
        JOptionPane.showMessageDialog(this, "Xoá thành công!");
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<KhachHang> findString(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<KhachHang> filterCategory(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        txt_makh.setText("");
        txt_tenkh.setText("");
        btgr_gt.clearSelection();
        txt_sdt.setText("");
        txt_diachi.setText("");
        txt_email.setText("");
        btgr_tt.clearSelection();
        JOptionPane.showMessageDialog(this, "clear thành công!");
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void phanquyen(){
        String vt = pnl_DangNhap.maVT;
        if (vt.equals("NV")) {
            btn_sua.setEnabled(false);
            btn_xoa.setEnabled(false);
        } else if(vt.equals("ADMIN")){
            btn_sua.setEnabled(true);
            btn_xoa.setEnabled(true);
        }
    }
}
