/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.formdev.flatlaf.FlatLightLaf;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import controller.Controller_ThongKe;
import daoipml.Daoipm_ThongKe;
import entity.Nam;
import entity.ThongKeDoanhThu;
import entity.ThongKeSanPham;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import java.io.File;
import java.io.FileOutputStream;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author DELL
 */
public class Pnl_2_ThongKeSanPham extends javax.swing.JPanel implements Controller_ThongKe{
    Daoipm_ThongKe repoTK = new Daoipm_ThongKe();
    DefaultTableModel model = new DefaultTableModel();
    int index = -1;
    DatePickerSettings settings = new DatePickerSettings();
    DatePicker datePickerStart = new DatePicker();
    DatePicker datePickerEnd = new DatePicker();

    /**
     * Creates new form panel_1_sanPhamA
     */
    public Pnl_2_ThongKeSanPham() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        initComponents();
        this.fillTableSanPham();
        this.fillToCboNam();
        this.fillToCbothang();
        this.fillToCbo();
        pnl_dateTime.setVisible(false);
        section_1.remove(pnl_chart);
        this.initDefaultThongKe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbo_thoiGian = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        pnl_dateTime = new javax.swing.JPanel();
        date_PickerStart = new com.github.lgooddatepicker.components.DatePicker();
        date_PickerEnd = new com.github.lgooddatepicker.components.DatePicker();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_timkiemsp1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jbl_doanhThuNam = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbl_don = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jbl_thanhCongDonNgay = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jbl_huyDonNgay = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbl_doanhThuNgay = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jbl_thanhCongDoanhThuNgay = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jbl_huyDonDoanhThuNgay = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jbl_doanhThuThang = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbl_thanhCongDoanhThuThang = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jbl_huyDonDoanhThuThang = new javax.swing.JLabel();
        section_1 = new javax.swing.JTabbedPane();
        section_1_tab_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_doanhThu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        section_2_tab_2 = new javax.swing.JPanel();
        field_1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbo_nam = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btn_load = new javax.swing.JButton();
        field_3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbo_thang = new javax.swing.JComboBox<>();
        section_2_tab_3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        section_1_tab2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sanPham = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        pnl_chart = new javax.swing.JPanel();

        setBackground(new java.awt.Color(235, 249, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 159, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(14, 159, 105));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Mốc thời gian thống kê:");
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 103, 11));

        cbo_thoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_thoiGian.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        cbo_thoiGian.setForeground(new java.awt.Color(6, 71, 46));
        cbo_thoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_thoiGianActionPerformed(evt);
            }
        });
        jPanel2.add(cbo_thoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 80, 17));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PHIẾU THỐNG KÊ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 9, 132, 11));
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -30, -1, -1));
        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -40, -1, -1));

        pnl_dateTime.setBackground(new java.awt.Color(14, 159, 105));
        pnl_dateTime.setFocusCycleRoot(true);

        date_PickerStart.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        date_PickerEnd.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        jLabel14.setText("Đến");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);

        jLabel13.setText("Từ ngày");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));

        btn_timkiemsp1.setText("xem");
        btn_timkiemsp1.setBackground(new java.awt.Color(38, 159, 114));
        btn_timkiemsp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiemsp1.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemsp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemsp1MouseClicked(evt);
            }
        });
        btn_timkiemsp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemsp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_dateTimeLayout = new javax.swing.GroupLayout(pnl_dateTime);
        pnl_dateTime.setLayout(pnl_dateTimeLayout);
        pnl_dateTimeLayout.setHorizontalGroup(
            pnl_dateTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dateTimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_PickerStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_PickerEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_timkiemsp1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_dateTimeLayout.setVerticalGroup(
            pnl_dateTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dateTimeLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnl_dateTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_PickerStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_PickerEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiemsp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnl_dateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 480, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, -1));

        jPanel6.setBackground(new java.awt.Color(239, 244, 242));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("TỔNG DOANH THU NĂM");
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(6, 71, 46));
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jbl_doanhThuNam.setText("0 vnd");
        jbl_doanhThuNam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbl_doanhThuNam.setForeground(new java.awt.Color(6, 71, 46));
        jPanel6.add(jbl_doanhThuNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 231, 100));

        jPanel7.setBackground(new java.awt.Color(239, 244, 242));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("TỔNG ĐƠN HÀNG");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 71, 46));
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jbl_don.setText("0 đơn");
        jbl_don.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbl_don.setForeground(new java.awt.Color(6, 71, 46));
        jPanel7.add(jbl_don, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(6, 71, 46));
        jLabel20.setText("Hủy:");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jbl_thanhCongDonNgay.setText("##");
        jbl_thanhCongDonNgay.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbl_thanhCongDonNgay.setForeground(new java.awt.Color(6, 71, 46));
        jPanel7.add(jbl_thanhCongDonNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel7.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 211, -1));
        jPanel7.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 211, 10));

        jLabel23.setText("Thành công:");
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(6, 71, 46));
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jbl_huyDonNgay.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbl_huyDonNgay.setForeground(new java.awt.Color(6, 71, 46));
        jbl_huyDonNgay.setText("##");
        jPanel7.add(jbl_huyDonNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 231, 100));

        jPanel3.setBackground(new java.awt.Color(239, 244, 242));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("TỔNG DOANH THU NGAY");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 71, 46));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jbl_doanhThuNgay.setText("0 VND");
        jbl_doanhThuNgay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbl_doanhThuNgay.setForeground(new java.awt.Color(6, 71, 46));
        jPanel3.add(jbl_doanhThuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        jLabel16.setText("Hủy:");
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(6, 71, 46));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jbl_thanhCongDoanhThuNgay.setText("##");
        jbl_thanhCongDoanhThuNgay.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbl_thanhCongDoanhThuNgay.setForeground(new java.awt.Color(6, 71, 46));
        jPanel3.add(jbl_thanhCongDoanhThuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 211, -1));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 211, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(6, 71, 46));
        jLabel17.setText("Thành công:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jbl_huyDonDoanhThuNgay.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbl_huyDonDoanhThuNgay.setForeground(new java.awt.Color(6, 71, 46));
        jbl_huyDonDoanhThuNgay.setText("##");
        jPanel3.add(jbl_huyDonDoanhThuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 231, 100));

        jPanel11.setBackground(new java.awt.Color(239, 244, 242));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(6, 71, 46));
        jLabel19.setText("TỔNG DOANH THU THÁNG");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jbl_doanhThuThang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbl_doanhThuThang.setForeground(new java.awt.Color(6, 71, 46));
        jbl_doanhThuThang.setText("0 VND");
        jPanel11.add(jbl_doanhThuThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        jLabel22.setText("Hủy:");
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(6, 71, 46));
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jbl_thanhCongDoanhThuThang.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbl_thanhCongDoanhThuThang.setForeground(new java.awt.Color(6, 71, 46));
        jbl_thanhCongDoanhThuThang.setText("##");
        jPanel11.add(jbl_thanhCongDoanhThuThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel11.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 211, -1));
        jPanel11.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 211, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(6, 71, 46));
        jLabel24.setText("Thành công:");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jbl_huyDonDoanhThuThang.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbl_huyDonDoanhThuThang.setForeground(new java.awt.Color(6, 71, 46));
        jbl_huyDonDoanhThuThang.setText("##");
        jPanel11.add(jbl_huyDonDoanhThuThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 231, 100));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 10, 1030, 160));

        section_1.setToolTipText("tab");
        section_1.setVerifyInputWhenFocusTarget(false);

        section_1_tab_1.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_1.setForeground(new java.awt.Color(6, 71, 46));
        section_1_tab_1.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(38, 159, 114));
        jScrollPane1.setForeground(new java.awt.Color(6, 71, 46));

        tbl_doanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tháng", "Sản phẩm bán ra", "Tổng giá bán", "Tổng giá giảm", "Tổng doanh thu"
            }
        ));
        tbl_doanhThu.setForeground(new java.awt.Color(6, 71, 46));
        jScrollPane1.setViewportView(tbl_doanhThu);
        if (tbl_doanhThu.getColumnModel().getColumnCount() > 0) {
            tbl_doanhThu.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbl_doanhThu.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        section_1_tab_1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 793, 413));

        jLabel3.setText("DANH SÁCH DOANH THU");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 71, 46));
        section_1_tab_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        section_2_tab_2.setBackground(new java.awt.Color(239, 244, 242));
        section_2_tab_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_2.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_1.setBackground(new java.awt.Color(250, 250, 250));
        field_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_1.setForeground(new java.awt.Color(250, 250, 250));
        field_1.setPreferredSize(new java.awt.Dimension(386, 637));
        field_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Năm:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 159, 103));
        field_1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        cbo_nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_nam.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        cbo_nam.setForeground(new java.awt.Color(6, 71, 46));
        field_1.add(cbo_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 120, 17));

        section_2_tab_2.add(field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 193, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(14, 159, 103));
        jLabel11.setText("Thiết lập hiển thị bảng doanh thu");
        section_2_tab_2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 179, 11));

        btn_load.setText("load");
        btn_load.setBackground(new java.awt.Color(14, 159, 103));
        btn_load.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_load.setForeground(new java.awt.Color(255, 255, 255));
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });
        section_2_tab_2.add(btn_load, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 167, 16));

        field_3.setBackground(new java.awt.Color(250, 250, 250));
        field_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_3.setForeground(new java.awt.Color(250, 250, 250));
        field_3.setPreferredSize(new java.awt.Dimension(386, 637));
        field_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 159, 103));
        jLabel8.setText("Tháng:");
        field_3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        cbo_thang.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        cbo_thang.setForeground(new java.awt.Color(6, 71, 46));
        cbo_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        field_3.add(cbo_thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1, 120, 17));

        section_2_tab_2.add(field_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 193, 20));

        section_1_tab_1.add(section_2_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 7, 193, 381));

        section_2_tab_3.setBackground(new java.awt.Color(239, 244, 242));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setText("Export excell");
        jButton10.setBackground(new java.awt.Color(14, 159, 103));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        section_2_tab_3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 8, 167, 16));

        jButton11.setText("Export");
        jButton11.setBackground(new java.awt.Color(14, 159, 103));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        section_2_tab_3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 30, 167, 16));

        section_1_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 397, 193, 56));

        section_1.addTab("Thống kê doanh thu", section_1_tab_1);

        section_1_tab2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(38, 159, 114));
        jScrollPane2.setForeground(new java.awt.Color(6, 71, 46));

        tbl_sanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Loại SP", "Tên SP", "Chất liệu", "Màu sắc", "Kích thước", "Số lượng tồn"
            }
        ));
        tbl_sanPham.setForeground(new java.awt.Color(6, 71, 46));
        jScrollPane2.setViewportView(tbl_sanPham);
        if (tbl_sanPham.getColumnModel().getColumnCount() > 0) {
            tbl_sanPham.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbl_sanPham.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        section_1_tab2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 793, 413));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(6, 71, 46));
        jLabel10.setText("DANH SÁCH SAN PHAM");
        section_1_tab2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        section_1.addTab("Thống kê sản phẩm", section_1_tab2);

        pnl_chart.setLayout(new java.awt.BorderLayout());
        section_1.addTab("Biểu đồ", pnl_chart);

        add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 165, 1027, 497));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timkiemsp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemsp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemsp1MouseClicked

    private void btn_timkiemsp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemsp1ActionPerformed
        // TODO add your handling code here:
        LocalDate from = date_PickerStart.getDate();
        LocalDate to = date_PickerEnd.getDate();
        thongKeTheoNgay(from, to);
        section_1.remove(pnl_chart);
    }//GEN-LAST:event_btn_timkiemsp1ActionPerformed

    private void cbo_thoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_thoiGianActionPerformed
        // TODO add your handling code here:
        Object obj = cbo_thoiGian.getSelectedItem();
        if(obj==null){
            return;
        }
        String tg = obj.toString();
        if (tg.equals("Hôm nay")) {
            pnl_dateTime.setVisible(false);
            thongKeHomNay();
            section_1.remove(pnl_chart);
        }else if(tg.equals("Theo Ngày")){
            pnl_dateTime.setVisible(true);
        }
    }//GEN-LAST:event_cbo_thoiGianActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        // TODO add your handling code here:
        int month = cbo_thang.getSelectedIndex();
        int year = Integer.parseInt(cbo_nam.getSelectedItem().toString());
        if(cbo_thang.getSelectedIndex()==0){
            if (section_1.indexOfComponent(pnl_chart) == -1) {
            section_1.addTab("Biểu đồ", pnl_chart);
        }
            thongKeTheoNam(year);
            chartDoanhThuNam(year);
        }else{
            if (section_1.indexOfComponent(pnl_chart) == -1) {
            section_1.addTab("Biểu đồ", pnl_chart);
            }   
            thongKeTheoThang(month, year);
            chartDoanhThuThang(month, year);
        }
    }//GEN-LAST:event_btn_loadActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        exportDoanhThuToExcel();
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_timkiemsp1;
    private javax.swing.JComboBox<String> cbo_nam;
    private javax.swing.JComboBox<String> cbo_thang;
    private javax.swing.JComboBox<String> cbo_thoiGian;
    private com.github.lgooddatepicker.components.DatePicker date_PickerEnd;
    private com.github.lgooddatepicker.components.DatePicker date_PickerStart;
    private javax.swing.JPanel field_1;
    private javax.swing.JPanel field_3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel jbl_doanhThuNam;
    private javax.swing.JLabel jbl_doanhThuNgay;
    private javax.swing.JLabel jbl_doanhThuThang;
    private javax.swing.JLabel jbl_don;
    private javax.swing.JLabel jbl_huyDonDoanhThuNgay;
    private javax.swing.JLabel jbl_huyDonDoanhThuThang;
    private javax.swing.JLabel jbl_huyDonNgay;
    private javax.swing.JLabel jbl_thanhCongDoanhThuNgay;
    private javax.swing.JLabel jbl_thanhCongDoanhThuThang;
    private javax.swing.JLabel jbl_thanhCongDonNgay;
    private javax.swing.JPanel pnl_chart;
    private javax.swing.JPanel pnl_dateTime;
    private javax.swing.JTabbedPane section_1;
    private javax.swing.JPanel section_1_tab2;
    private javax.swing.JPanel section_1_tab_1;
    private javax.swing.JPanel section_2_tab_2;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JTable tbl_doanhThu;
    private javax.swing.JTable tbl_sanPham;
    // End of variables declaration//GEN-END:variables
    public void formatDate() {
        DatePickerSettings settings = new DatePickerSettings();
        settings.setFormatForDatesCommonEra("yyyy-MM-dd");

//        settings.setMonthFormatter(month -> String.format("%02d", month.getValue()));// Month dropdown show as numbers (01-12)
        DatePicker datePicker = new DatePicker(settings);
        date_PickerStart.add(datePicker);
        date_PickerEnd.add(datePicker);

    }
    public void fillToCbo() {
        cbo_thoiGian.removeAllItems();
        cbo_thoiGian.addItem("Hôm nay");        // value = 0
        cbo_thoiGian.addItem("Theo Ngày"); 
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void fillToCboNam() {
        cbo_nam.removeAllItems();
        List<Nam> list=repoTK.loatNam();
        for(Nam x:list){
            cbo_nam.addItem(String.valueOf(x.getNam()));
        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void fillToCbothang() {
        cbo_thang.removeAllItems();
        cbo_thang.addItem("All");
        for(int i = 1;i<=12;i++){
            cbo_thang.addItem(String.valueOf(i));
        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    @Override
    public void thongKeHomNay() {
    List<ThongKeDoanhThu> list = repoTK.homNay();

    if (!list.isEmpty()) {
        ThongKeDoanhThu dt = list.get(0);

        jbl_don.setText(dt.getSoDon() + " đơn");

        jbl_doanhThuNgay.setText(dt.getTongDoanhThu() + " VND");

        jbl_thanhCongDonNgay.setText(String.valueOf(dt.getDonThanhCong()));
        jbl_huyDonNgay.setText(String.valueOf(dt.getDonHuy()));

        jbl_thanhCongDoanhThuNgay.setText(String.valueOf(dt.getDonThanhCong()));
        jbl_huyDonDoanhThuNgay.setText(String.valueOf(dt.getDonHuy()));
    }

    }
    @Override
    public void thongKeTheoNgay(LocalDate from, LocalDate to) {
    List<ThongKeDoanhThu> list = repoTK.theoNgay(from, to);

    if (!list.isEmpty()) {
        ThongKeDoanhThu dt = list.get(0);

        jbl_don.setText(dt.getSoDon() + " đơn");
        jbl_doanhThuNgay.setText(dt.getTongDoanhThu() + " VND");

        jbl_thanhCongDonNgay.setText(String.valueOf(dt.getDonThanhCong()));
        jbl_huyDonNgay.setText(String.valueOf(dt.getDonHuy()));

        jbl_thanhCongDoanhThuNgay.setText(String.valueOf(dt.getDonThanhCong()));
        jbl_huyDonDoanhThuNgay.setText(String.valueOf(dt.getDonHuy()));
    }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void thongKeTheoThang(int month, int year) {
    model = (DefaultTableModel) tbl_doanhThu.getModel();
    model.setRowCount(0);

    List<ThongKeDoanhThu> list = repoTK.theoThang(month, year);

    for (ThongKeDoanhThu dt : list) {
        model.addRow(new Object[]{
            dt.getThang(),
            dt.getSoSanPhamBan(),
            dt.getTongGiaBan(),
            dt.getTongGiamGia(),
            dt.getTongDoanhThu()
        });
    }

    if (!list.isEmpty()) {
        ThongKeDoanhThu dt = list.get(0);

        jbl_doanhThuThang.setText(dt.getTongDoanhThu() + " VND");
        jbl_thanhCongDoanhThuThang.setText(String.valueOf(dt.getDonThanhCong()));
        jbl_huyDonDoanhThuThang.setText(String.valueOf(dt.getDonHuy()));
    }
}
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

    @Override
    public void thongKeTheoNam(int year) {
    List<ThongKeDoanhThu> list = repoTK.theoNam(year);
    model = (DefaultTableModel) tbl_doanhThu.getModel();
    model.setRowCount(0);
        for (ThongKeDoanhThu dt : list) {
        model.addRow(new Object[]{
            dt.getThang(),
            dt.getSoSanPhamBan(),
            dt.getTongGiaBan(),
            dt.getTongGiamGia(),
            dt.getTongDoanhThu()
        });
    }
    // không có dữ liệu
    if (list.isEmpty()) {
        jbl_doanhThuNam.setText("0 VND");
        return;
    }


    BigDecimal tongNam = BigDecimal.ZERO;
    for (ThongKeDoanhThu dt : list) {
        if (dt.getTongDoanhThu() != null) {
            tongNam = tongNam.add(dt.getTongDoanhThu());
        }
    }


    NumberFormat vnFormat = NumberFormat.getInstance(new Locale("vi", "VN"));
    String tienFormat = vnFormat.format(tongNam);

    jbl_doanhThuNam.setText(tienFormat + " VND");
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    @Override
    public void fillTableDoanhThu(List<ThongKeDoanhThu> list) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillTableSanPham() {
        model = (DefaultTableModel) tbl_sanPham.getModel();
        model.setRowCount(0);
        int stt=1;
        for (ThongKeSanPham sp : repoTK.tatCaSanPham()) {
        model.addRow(new Object[]{
            stt++,
            sp.getMaSP(),
            sp.getLoaiSP(),
            sp.getTenSP(),
            sp.getChatLieu(),
            sp.getMauSac(),
            sp.getKichThuoc(),
            sp.getSoLuongTon()
    });
    }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void chartDoanhThuThang(int month, int year) {
    List<ThongKeDoanhThu> list = repoTK.theoThang(month, year);
    if (list == null || list.isEmpty()) return;

    ThongKeDoanhThu tk = list.get(0);

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    String label = "Tháng " + month + "/" + year;

    // Doanh thu
    dataset.addValue(tk.getTongDoanhThu(), "Doanh thu (VND)", label);

    // Hệ số scale để nhìn rõ cột đơn hàng
    int heSo = 100_000;

    // 3 trạng thái đơn
    dataset.addValue(tk.getDonThanhCong() * heSo, "Đơn thành công (x100k)", label);
    dataset.addValue(tk.getDonHuy() * heSo, "Đơn hủy (x100k)", label);

    // Tạo biểu đồ
    JFreeChart chart = ChartFactory.createBarChart(
            "Thống kê tháng " + month + "/" + year,
            "Thống số",
            "Giá trị (VND)",
            dataset
    );

    // Màu
    CategoryPlot plot = chart.getCategoryPlot();
    BarRenderer renderer = (BarRenderer) plot.getRenderer();

    renderer.setSeriesPaint(0, new Color(250, 90, 90));  
    renderer.setSeriesPaint(1, new Color(70, 120, 255)); 
    renderer.setSeriesPaint(2, new Color(60, 200, 80));   
    renderer.setItemMargin(0.1);

    pnl_chart.removeAll();
    pnl_chart.setLayout(new BorderLayout());
    pnl_chart.add(new ChartPanel(chart), BorderLayout.CENTER);
    pnl_chart.validate();
}

    public void chartDoanhThuNam(int year) {
    // 1️⃣ Lấy dữ liệu từ SQL
    List<ThongKeDoanhThu> list = repoTK.theoNam(year);

    // 2️⃣ Dataset cho JFreeChart
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    for (ThongKeDoanhThu dt : list) {
        dataset.addValue(
            dt.getTongDoanhThu(),      
            "Doanh thu",               
            "Tháng " + dt.getThang()   
        );
    }
    //taoj chart dangh cột
    JFreeChart chart = ChartFactory.createBarChart(
            "Biểu đồ doanh thu năm " + year,
            "Tháng",
            "Doanh thu (VND)",
            dataset
    );


    ChartPanel chartPanel = new ChartPanel(chart);

    // 5️⃣ Nhét vào pnl_chart
    pnl_chart.removeAll();
    pnl_chart.setLayout(new BorderLayout());
    pnl_chart.add(chartPanel, BorderLayout.CENTER);

    pnl_chart.validate();
    pnl_chart.repaint();
    }
    public void exportDoanhThuToExcel() {
    JFileChooser fc = new JFileChooser();
    fc.setDialogTitle("Chọn nơi lưu file");

    // Tên file mặc định
    fc.setSelectedFile(new File("BShoesTK.xlsx"));

    int userSelection = fc.showSaveDialog(null);
    if (userSelection != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File fileToSave = fc.getSelectedFile();


    if (!fileToSave.getName().toLowerCase().endsWith(".xlsx")) {
        fileToSave = new File(fileToSave.toString() + ".xlsx");
    }

    try (Workbook workbook = new XSSFWorkbook()) {
        Sheet sheet = workbook.createSheet("DoanhThu");

        // Style Header
        CellStyle headerStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        headerStyle.setFont(font);

        // Ghi Header
        Row headerRow = sheet.createRow(0);
        for (int i = 0; i < tbl_doanhThu.getColumnCount(); i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(tbl_doanhThu.getColumnName(i));
            cell.setCellStyle(headerStyle);
        }

        // Ghi dữ liệu
        for (int i = 0; i < tbl_doanhThu.getRowCount(); i++) {
            Row row = sheet.createRow(i + 1);
            for (int j = 0; j < tbl_doanhThu.getColumnCount(); j++) {
                Object value = tbl_doanhThu.getValueAt(i, j);
                row.createCell(j).setCellValue(value == null ? "" : value.toString());
            }
        }

        // Auto-size column
        for (int i = 0; i < tbl_doanhThu.getColumnCount(); i++) {
            sheet.autoSizeColumn(i);
        }

        // Ghi file
        try (FileOutputStream fos = new FileOutputStream(fileToSave)) {
            workbook.write(fos);
        }

        JOptionPane.showMessageDialog(null, 
                "Xuất file thành công!\n" + fileToSave.getAbsolutePath());

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, 
                "Có lỗi xảy ra khi xuất file!");
    }
}
    private void initDefaultThongKe() {
    // Lấy thời gian hiện tại
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    int month = now.getMonthValue();
    thongKeTheoNam(year);
    thongKeTheoThang(month, year);}
}
