/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import daoipml.DaoImpl_HoaDon;
import daoipml.DaoImpl_HoaDonChiTiet;
import daoipml.DaoImpl_KhachHang;
import daoipml.DaoImpl_NhanVien;
import entity.HoaDon;
import entity.HoaDonChiTiet;
import entity.KhachHang;
import entity.NhanVien;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author Nguyen Trung Nghia
 */
public class Pnl_PhieuTamTinh extends javax.swing.JPanel {

    private int idHoaDon;
    private DaoImpl_HoaDon repoHD = new DaoImpl_HoaDon();
    private DaoImpl_HoaDonChiTiet repoHDCT = new DaoImpl_HoaDonChiTiet();
    private DaoImpl_KhachHang repoKH = new DaoImpl_KhachHang();
    private DaoImpl_NhanVien repoNV = new DaoImpl_NhanVien();

    private JTextArea area;

    public Pnl_PhieuTamTinh(int idHoaDon) {
        this.idHoaDon = idHoaDon;
        initUI();
        loadData();
    }
    private BigDecimal safeBig(Object value) {
        if (value == null) return BigDecimal.ZERO;

        try {
            return new BigDecimal(value.toString().trim());
        } catch (Exception e) {
            return BigDecimal.ZERO;
        }
    }
    
    private String center(String text, int width) {
        int pad = (width - text.length()) / 2;
        if (pad < 0) pad = 0;
        return " ".repeat(pad) + text;
    }

    private void initUI() {
        setLayout(new BorderLayout());

        area = new JTextArea();
        area.setEditable(false);
        area.setFont(new Font("Courier New", Font.PLAIN, 16));

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(900, 600)); 

        add(scroll, BorderLayout.CENTER);
    }
    private String safeMoney(Object value) {
    try {
        if (value == null) return "0";

        BigDecimal bd = new BigDecimal(value.toString().trim());
        NumberFormat vn = NumberFormat.getInstance(new Locale("vi", "VN"));

        return vn.format(bd);
    } catch (Exception e) {
        return "0";
    }
}
    private void loadData() {
        HoaDon hd = repoHD.findById(idHoaDon);
        KhachHang kh = repoKH.findById(hd.getId_khach_hang());
        NhanVien nv = repoNV.findById(hd.getId_nhan_vien());
        List<HoaDonChiTiet> list = repoHDCT.findBYHoaDon(idHoaDon);

        NumberFormat vn = NumberFormat.getInstance(new Locale("vi", "VN"));

        String headerFormat = "%-4s %-40s %-5s %-12s %-12s\n";
        String rowFormat    = "%-4s %-40s %-5s %-12s %-12s\n";

        StringBuilder sb = new StringBuilder();
        int width = 80;

        sb.append(center("BShoes", width)).append("\n");
        sb.append(center("*** PHIẾU TẠM TÍNH ***", width)).append("\n\n");

        sb.append("Mã hóa đơn: ").append(hd.getMa_hoa_don()).append("\n");
        sb.append("Ngày tạo:  ").append(hd.getNgay_tao_ma()).append("\n");
        sb.append("Khách hàng: ")
                .append(kh != null ? kh.getTen_khach_hang() : "---").append("\n");
        sb.append("SDT: ").append(kh != null ? kh.getSo_dien_thoai() : "---").append("\n");
        sb.append("Nhân viên: ").append(nv != null ? nv.getTen_nhan_vien() : "---").append("\n\n");

        sb.append("-".repeat(width)).append("\n");
        sb.append(String.format(headerFormat,"STT","Sản phẩm","SL","Giá","Thành tiền"));
        sb.append("-".repeat(width)).append("\n");
        int i = 1;
        for (HoaDonChiTiet ct : list) {
            String ten = ct.getTen_san_pham() == null ? "" : ct.getTen_san_pham();
            if (ten.length() > 40) ten = ten.substring(0, 40);

            sb.append(String.format(rowFormat,
                    i++,
                    ten,
                    ct.getSo_luong(),
                    safeMoney(ct.getDon_gia()),
                    safeMoney(ct.getThanh_tien())
            ));
        }

        sb.append("-".repeat(width)).append("\n\n");

        sb.append(String.format("%-20s %s\n", "Tổng tiền:", safeMoney(hd.getTong_tien_ban_dau())));
        sb.append(String.format("%-20s - %s\n", "Giảm giá:", safeMoney(hd.getTien_giam_gia())));
        sb.append(String.format("%-20s %s\n", "THÀNH TIỀN:", safeMoney(hd.getTong_tien_phai_tra())));

        sb.append("-".repeat(width)).append("\n\n");
        sb.append(center("Cảm ơn quý khách!", width)).append("\n");

        area.setText(sb.toString());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
