/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import com.formdev.flatlaf.FlatLightLaf;
import controller.Controller_LichSuHoaDon;
import daoipml.*;
import entity.HoaDon;
import entity.KhachHang;
import entity.LichSuHoaDon;
import entity.NhanVien;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Pnl_7_LichSuHoaDon extends javax.swing.JPanel implements Controller_LichSuHoaDon{
    private DaoImpl_LichSuHoaDon repoLSHoaDon = new DaoImpl_LichSuHoaDon();
    private DaoImpl_NhanVien repoNhanVien = new DaoImpl_NhanVien();
    private DaoImpl_KhachHang repoKhachHang = new DaoImpl_KhachHang();
    private DaoImpl_HoaDon repoHoaDon = new DaoImpl_HoaDon();
    private DaoImpl_SanPhamChiTiet_hd repoHoanTra = new DaoImpl_SanPhamChiTiet_hd();
    
    private List<LichSuHoaDon> listLSHoaDon = List.of();
    private List<LichSuHoaDon> listLSHoanTra = List.of();
    
    private DefaultTableModel molLSHoaDon =  new DefaultTableModel();
    private DefaultTableModel molLSHoanTra =  new DefaultTableModel();
    private int index = -1;
    Object[] ttDonHang ={  "Đang tạo","Đã thanh toán","Hủy đơn","Chờ giao hàng","Đã giao","Trả hàng"};

    /**
     * Creates new form panel_1_sanPhamA
     */
    public Pnl_7_LichSuHoaDon() {
        // init ui theme
        try {
            FlatLightLaf.setup(); // Consistent flat look
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        initComponents();
        bar_search.setVisible(false);
        
        this.fillToTable();
        tbl_lichSu.getColumnModel().getColumn(1).setMinWidth(0);
        tbl_lichSu.getColumnModel().getColumn(1).setMaxWidth(0);
        tbl_lichSu.getColumnModel().getColumn(1).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdogrp_thanhToan = new javax.swing.ButtonGroup();
        rdogrp_giaoHang = new javax.swing.ButtonGroup();
        section_2 = new javax.swing.JTabbedPane();
        section_2_tab_1 = new javax.swing.JPanel();
        section_2_tab_2 = new javax.swing.JPanel();
        field_1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_idHoaDon = new javax.swing.JLabel();
        field_6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbl_tenKhachHang = new javax.swing.JLabel();
        field_20 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        lbl_khachHangSDT = new javax.swing.JLabel();
        field_21 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lbl_hoaDonTien = new javax.swing.JLabel();
        field_22 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lbl_hoaDonNgayTao = new javax.swing.JLabel();
        field_23 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        rdo_thanhToan_1 = new javax.swing.JRadioButton();
        rdo_thanhToan_2 = new javax.swing.JRadioButton();
        field_24 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        rdo_giaoHang_1 = new javax.swing.JRadioButton();
        rdo_giaoHang_2 = new javax.swing.JRadioButton();
        field_4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_hoaDonGhiChu = new javax.swing.JTextField();
        field_29 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        lbl_idNhanVien = new javax.swing.JLabel();
        field_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_tenNhanVien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        section_2_tab_3 = new javax.swing.JPanel();
        btn_lammoi = new javax.swing.JButton();
        section_1_tab_1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bar_search = new javax.swing.JPanel();
        txt_timkiemsp = new javax.swing.JTextField();
        btn_timkiemsp = new javax.swing.JButton();
        scollpanel = new javax.swing.JScrollPane();
        tbl_lichSu = new javax.swing.JTable();

        setBackground(new java.awt.Color(235, 249, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_1.setBackground(new java.awt.Color(14, 159, 105));
        section_2_tab_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_1.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        section_2_tab_2.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_2.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_2.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_1.setBackground(new java.awt.Color(250, 250, 250));
        field_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_1.setForeground(new java.awt.Color(250, 250, 250));
        field_1.setPreferredSize(new java.awt.Dimension(386, 637));
        field_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 159, 103));
        jLabel6.setText("id hóa đơn:");
        field_1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_idHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_idHoaDon.setForeground(new java.awt.Color(14, 159, 103));
        lbl_idHoaDon.setText("...");
        field_1.add(lbl_idHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 20));

        field_6.setBackground(new java.awt.Color(250, 250, 250));
        field_6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_6.setForeground(new java.awt.Color(250, 250, 250));
        field_6.setPreferredSize(new java.awt.Dimension(386, 637));
        field_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(14, 159, 103));
        jLabel11.setText("Tên khách hàng:");
        field_6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_tenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_tenKhachHang.setForeground(new java.awt.Color(14, 159, 103));
        lbl_tenKhachHang.setText("...");
        field_6.add(lbl_tenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 20));

        field_20.setBackground(new java.awt.Color(255, 255, 255));
        field_20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_20.setForeground(new java.awt.Color(250, 250, 250));
        field_20.setPreferredSize(new java.awt.Dimension(386, 637));
        field_20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(14, 159, 103));
        jLabel31.setText("SDT:");
        field_20.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_khachHangSDT.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_khachHangSDT.setForeground(new java.awt.Color(14, 159, 103));
        lbl_khachHangSDT.setText("...");
        field_20.add(lbl_khachHangSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 20));

        field_21.setBackground(new java.awt.Color(250, 250, 250));
        field_21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_21.setForeground(new java.awt.Color(250, 250, 250));
        field_21.setPreferredSize(new java.awt.Dimension(386, 637));
        field_21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(14, 159, 103));
        jLabel32.setText("Tổng tiền hàng:");
        field_21.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_hoaDonTien.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_hoaDonTien.setForeground(new java.awt.Color(14, 159, 103));
        lbl_hoaDonTien.setText("...");
        field_21.add(lbl_hoaDonTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 20));

        field_22.setBackground(new java.awt.Color(255, 255, 255));
        field_22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_22.setForeground(new java.awt.Color(250, 250, 250));
        field_22.setPreferredSize(new java.awt.Dimension(386, 637));
        field_22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(14, 159, 103));
        jLabel33.setText("Ngày tạo:");
        field_22.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_hoaDonNgayTao.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_hoaDonNgayTao.setForeground(new java.awt.Color(14, 159, 103));
        lbl_hoaDonNgayTao.setText("...");
        field_22.add(lbl_hoaDonNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 20));

        field_23.setBackground(new java.awt.Color(250, 250, 250));
        field_23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_23.setForeground(new java.awt.Color(250, 250, 250));
        field_23.setPreferredSize(new java.awt.Dimension(386, 637));
        field_23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(14, 159, 103));
        jLabel35.setText("Thanh toán:");
        field_23.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        rdogrp_thanhToan.add(rdo_thanhToan_1);
        rdo_thanhToan_1.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_thanhToan_1.setText("Đã thanh toán");
        field_23.add(rdo_thanhToan_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 100, 17));

        rdogrp_thanhToan.add(rdo_thanhToan_2);
        rdo_thanhToan_2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_thanhToan_2.setText("Chưa thanh toán");
        field_23.add(rdo_thanhToan_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 17));

        section_2_tab_2.add(field_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 360, 20));

        field_24.setBackground(new java.awt.Color(255, 255, 255));
        field_24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_24.setForeground(new java.awt.Color(250, 250, 250));
        field_24.setPreferredSize(new java.awt.Dimension(386, 637));
        field_24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(14, 159, 103));
        jLabel21.setText("Trạng thái hàng:");
        field_24.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        rdogrp_giaoHang.add(rdo_giaoHang_1);
        rdo_giaoHang_1.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_giaoHang_1.setText("Đã giao");
        field_24.add(rdo_giaoHang_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 100, 17));

        rdogrp_giaoHang.add(rdo_giaoHang_2);
        rdo_giaoHang_2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        rdo_giaoHang_2.setText("Hoàn trả");
        field_24.add(rdo_giaoHang_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 17));

        section_2_tab_2.add(field_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 360, 20));

        field_4.setBackground(new java.awt.Color(255, 255, 255));
        field_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_4.setForeground(new java.awt.Color(250, 250, 250));
        field_4.setPreferredSize(new java.awt.Dimension(386, 637));
        field_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(14, 159, 103));
        jLabel9.setText("Ghi chú:");
        field_4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_hoaDonGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        field_4.add(lbl_hoaDonGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 1, 240, 80));

        section_2_tab_2.add(field_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 360, 82));

        field_29.setBackground(new java.awt.Color(255, 255, 255));
        field_29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_29.setForeground(new java.awt.Color(250, 250, 250));
        field_29.setPreferredSize(new java.awt.Dimension(386, 637));
        field_29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(14, 159, 103));
        jLabel40.setText("Mã nhân viên:");
        field_29.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_idNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_idNhanVien.setForeground(new java.awt.Color(14, 159, 103));
        lbl_idNhanVien.setText("...");
        field_29.add(lbl_idNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 20));

        field_5.setBackground(new java.awt.Color(255, 255, 255));
        field_5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        field_5.setForeground(new java.awt.Color(250, 250, 250));
        field_5.setPreferredSize(new java.awt.Dimension(386, 637));
        field_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 159, 103));
        jLabel10.setText("Tên nhân viên:");
        field_5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, 100, 11));

        lbl_tenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl_tenNhanVien.setForeground(new java.awt.Color(14, 159, 103));
        lbl_tenNhanVien.setText("...");
        field_5.add(lbl_tenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 4, 240, 11));

        section_2_tab_2.add(field_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 20));

        section_2_tab_1.add(section_2_tab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, 360, 394));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thông tin");
        section_2_tab_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, 15));

        section_2_tab_3.setBackground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        section_2_tab_3.setForeground(new java.awt.Color(250, 250, 250));
        section_2_tab_3.setPreferredSize(new java.awt.Dimension(386, 637));
        section_2_tab_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_lammoi.setBackground(new java.awt.Color(14, 159, 103));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setText("Làm mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        section_2_tab_3.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, 333, 16));

        section_2_tab_1.add(section_2_tab_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 442, 360, 180));

        section_2.addTab("Chi tiết", section_2_tab_1);

        add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, -5, 386, 672));

        section_1_tab_1.setBackground(new java.awt.Color(250, 250, 250));
        section_1_tab_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        section_1_tab_1.setForeground(new java.awt.Color(6, 71, 46));
        section_1_tab_1.setPreferredSize(new java.awt.Dimension(613, 637));
        section_1_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 71, 46));
        jLabel3.setText("Lịch Sử Hóa đơn");
        section_1_tab_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 7, -1, -1));

        bar_search.setBackground(new java.awt.Color(38, 159, 114));
        bar_search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_timkiemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemspActionPerformed(evt);
            }
        });
        bar_search.add(txt_timkiemsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3, 142, 18));

        btn_timkiemsp.setBackground(new java.awt.Color(38, 159, 114));
        btn_timkiemsp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiemsp.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemsp.setText("Tìm Kiếm");
        btn_timkiemsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemspMouseClicked(evt);
            }
        });
        btn_timkiemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemspActionPerformed(evt);
            }
        });
        bar_search.add(btn_timkiemsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 3, 128, 18));

        section_1_tab_1.add(bar_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, 290, 24));

        tbl_lichSu.setForeground(new java.awt.Color(6, 71, 46));
        tbl_lichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID", "ID hóa đơn", "ID NV", "Ngày tạo", "Ngày cập nhật", "TT thanh toán", "Ghi chú"
            }
        ));
        tbl_lichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lichSuMouseClicked(evt);
            }
        });
        scollpanel.setViewportView(tbl_lichSu);
        if (tbl_lichSu.getColumnModel().getColumnCount() > 0) {
            tbl_lichSu.getColumnModel().getColumn(0).setPreferredWidth(32);
        }

        section_1_tab_1.add(scollpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 587, 580));

        add(section_1_tab_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 29, 613, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        fillToTable();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void txt_timkiemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemspActionPerformed
        //timTheoMa(txt_timkiemsp.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemspActionPerformed

    private void btn_timkiemspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemspMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemspMouseClicked

    private void btn_timkiemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemspActionPerformed
        // TODO add your handling code here:
//        fillToTableByDate();
        
    }//GEN-LAST:event_btn_timkiemspActionPerformed

    private void tbl_lichSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lichSuMouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tbl_lichSuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar_search;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_timkiemsp;
    private javax.swing.JPanel field_1;
    private javax.swing.JPanel field_20;
    private javax.swing.JPanel field_21;
    private javax.swing.JPanel field_22;
    private javax.swing.JPanel field_23;
    private javax.swing.JPanel field_24;
    private javax.swing.JPanel field_29;
    private javax.swing.JPanel field_4;
    private javax.swing.JPanel field_5;
    private javax.swing.JPanel field_6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lbl_hoaDonGhiChu;
    private javax.swing.JLabel lbl_hoaDonNgayTao;
    private javax.swing.JLabel lbl_hoaDonTien;
    private javax.swing.JLabel lbl_idHoaDon;
    private javax.swing.JLabel lbl_idNhanVien;
    private javax.swing.JLabel lbl_khachHangSDT;
    private javax.swing.JLabel lbl_tenKhachHang;
    private javax.swing.JLabel lbl_tenNhanVien;
    private javax.swing.JRadioButton rdo_giaoHang_1;
    private javax.swing.JRadioButton rdo_giaoHang_2;
    private javax.swing.JRadioButton rdo_thanhToan_1;
    private javax.swing.JRadioButton rdo_thanhToan_2;
    private javax.swing.ButtonGroup rdogrp_giaoHang;
    private javax.swing.ButtonGroup rdogrp_thanhToan;
    private javax.swing.JScrollPane scollpanel;
    private javax.swing.JPanel section_1_tab_1;
    private javax.swing.JTabbedPane section_2;
    private javax.swing.JPanel section_2_tab_1;
    private javax.swing.JPanel section_2_tab_2;
    private javax.swing.JPanel section_2_tab_3;
    private javax.swing.JTable tbl_lichSu;
    private javax.swing.JTextField txt_timkiemsp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(LichSuHoaDon entity) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public LichSuHoaDon getForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
        int stt=0;
        molLSHoaDon = (DefaultTableModel) tbl_lichSu.getModel();
        molLSHoaDon.setRowCount(0);
        listLSHoaDon = repoLSHoaDon.findAll();
        for(LichSuHoaDon x: listLSHoaDon){
            Object[] data = new Object[]{
                stt++,
                x.getId(),
                x.getId_hoa_don(),
                x.getId_nhan_vien(),
//                repoNhanVien.findById(x.getId_nhan_vien()).getTen_nhan_vien(),
                x.getNgay_tao_ma(),
                x.getNgay_cap_nhat(),
                ttDonHang[repoHoaDon.findById(x.getId_hoa_don()).getTrang_thai()],
//                "Đã thanh toán",
                x.getGhi_chu()
            };
            molLSHoaDon.addRow(data);
        }

        //fill hóa đơn đã bị hủy
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void fillToTableByDate() {
        String timKiem = "%"+ txt_timkiemsp.getText()+"%";
        int stt=0;
        molLSHoaDon = (DefaultTableModel) tbl_lichSu.getModel();
        molLSHoaDon.setRowCount(0);
        listLSHoaDon = repoLSHoaDon.findAllByDate(timKiem);
        for(LichSuHoaDon x: listLSHoaDon){
            Object[] data = new Object[]{
                stt++,
                x.getId(),
                x.getId_hoa_don(),
                x.getId_nhan_vien(),
//                repoNhanVien.findById(x.getId_nhan_vien()).getTen_nhan_vien(),
                x.getNgay_tao_ma(),
                x.getNgay_cap_nhat(),
                ttDonHang[repoHoaDon.findById(x.getId_hoa_don()).getTrang_thai()],
//                "Đã thanh toán",
                x.getGhi_chu()
            };
            molLSHoaDon.addRow(data);
        }

        //fill hóa đơn đã bị hủy
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToCbo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void edit() {
 int row = tbl_lichSu.getSelectedRow();
    if (row < 0) return;

    // Lấy đúng entity theo dòng
    LichSuHoaDon entity = listLSHoaDon.get(row);

    // Load nhân viên tạo lịch sử
    NhanVien nv = repoNhanVien.findById(entity.getId_nhan_vien());
    if (nv != null) {
        lbl_idNhanVien.setText(nv.getMa_nhan_vien());
        lbl_tenNhanVien.setText(nv.getTen_nhan_vien());
    } else {
        lbl_idNhanVien.setText("N/A");
        lbl_tenNhanVien.setText("Không tìm thấy");
    }

    // Load hóa đơn gốc
    HoaDon hd = repoHoaDon.findById(entity.getId_hoa_don());
    if (hd != null) {
        lbl_idHoaDon.setText(String.valueOf(hd.getId_hoa_don()));

        lbl_hoaDonTien.setText(String.valueOf(hd.getTong_tien_phai_tra()));
        lbl_hoaDonNgayTao.setText(String.valueOf(entity.getNgay_tao_ma()));
        lbl_hoaDonGhiChu.setText(entity.getGhi_chu() == null ? "" : entity.getGhi_chu());

        // Load khách hàng
        if (hd.getId_khach_hang() > 0) {
            KhachHang kh = repoKhachHang.findById(hd.getId_khach_hang());
            if (kh != null) {
                lbl_tenKhachHang.setText(kh.getTen_khach_hang());
                lbl_khachHangSDT.setText(kh.getSo_dien_thoai());
            }
        } else {
            lbl_tenKhachHang.setText("Khách lẻ");
            lbl_khachHangSDT.setText("N/A");
        }

        // Trạng thái hóa đơn
        int tt = hd.getTrang_thai();
        rdo_thanhToan_1.setSelected(tt == 1);
        rdo_thanhToan_2.setSelected(tt != 1);

        rdo_giaoHang_1.setSelected(tt == 4);
        rdo_giaoHang_2.setSelected(tt == 5);
    }
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void create() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<LichSuHoaDon> findString(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<LichSuHoaDon> filterCategory(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
